### ISSUE TITLE
左右两侧控制按钮中加入逐次切换播放模式功能

### ISSUE THREAD

**Issue by raindropQWQ** [Steve-xmh/applemusic-like-lyrics#101]
像网易云原本那样，按一次切换到列表循环，再按一次切换到单曲循环，之后是随机播放，顺序播放，最后回到列表循环
（如果在播放“我喜欢的音乐”则还有一个心动模式）

现在虽然能更改按钮作用，但一个按钮只能切换固定的一种播放模式，没法覆盖到所有播放模式

**Comment by cale044** [comment]
#80 你是否在找

**Comment by cale044** [comment]
我提过lssues了

**Comment by Steve-xmh** [comment]
已增加新按钮
