### ISSUE TITLE
前奏三点大小异常

### ISSUE THREAD

**Issue by raindropQWQ** [Steve-xmh/applemusic-like-lyrics#103]
![图片](https://user-images.githubusercontent.com/102001942/229231555-e0f895b9-dedd-4d59-8a0f-ce97d9c1aaf9.png)
如图，变得非常小

![图片](https://user-images.githubusercontent.com/102001942/229232325-0f2c7d7d-2132-4bc4-ba30-1f4eb005c4dd.png)
启用自定义字体大小后，三点可受字体大小控制，但仍不协调

**Comment by Steve-xmh** [comment]
其实是故意的（即答）
重新看了一眼 Apple Music 的三点发现没那么大就调小了
（我之前为啥会做大）

**Comment by raindropQWQ** [comment]
但是感觉一开始的这个蚂蚁大小调得像个节日笑话（
现在0.0.6的感觉也还是有点小了，我感觉Apple Music的应该也没有这么小
而且开了自定义字体大小后，这三点的间距会变得很不协调，间距感觉大于圆的半径了

**Comment by Steve-xmh** [comment]
> > 其实是故意的（即答） 重新看了一眼 Apple Music 的三点发现没那么大就调小了 （我之前为啥会做大）
> 
> 但是感觉一开始的这个蚂蚁大小调得像个节日笑话（ 现在0.0.6的感觉也还是有点小了，我感觉Apple Music的应该也没有这么小 而且开了自定义字体大小后，这三点的间距会变得很不协调，间距感觉大于圆的半径了

![image](https://user-images.githubusercontent.com/39523898/229289154-f663d4f1-e19c-4682-989f-20960fd11ab2.png)
摘自 Lyricify 截图
