### ISSUE TITLE
在播放列表不是“我喜欢的音乐”时，切换播放模式到心动模式会导致网易云卡死

### ISSUE THREAD

**Issue by raindropQWQ** [Steve-xmh/applemusic-like-lyrics#104]
如题，在播放其他非“我喜欢的音乐”歌单时，用循环切换播放模式按钮，或者是用单一切换心动模式按钮切换到心动模式，都会导致网易云卡死
此时无法对网易云进行任何操作，只能用任务管理器结束进程

**Comment by Steve-xmh** [comment]
已修正
