### ISSUE TITLE
播放“我的音乐云盘”内歌曲，无法正常显示歌词

### ISSUE THREAD

**Issue by Bacon257** [Steve-xmh/applemusic-like-lyrics#105]
播放“我的音乐云盘”内歌曲，选择“填写对应音乐ID”和“本地文件歌词”，都无法正常显示歌词。
版本：2.0-beta 0.05
![QQ截图20230401224837](https://user-images.githubusercontent.com/100892568/229296376-2f43f67b-800f-4519-b2f8-14134641f441.png)
![QQ截图20230401224910](https://user-images.githubusercontent.com/100892568/229296394-116391df-126c-45b0-873a-47cc0ec5d0b9.png)

**Comment by Steve-xmh** [comment]
如果可以，请录制一个视频来复现一下情况

**Comment by Steve-xmh** [comment]
哦，没注意看你的插件版本，这个问题刚刚修了，之后会更新的。

**Comment by Bacon257** [comment]
> 哦，没注意看你的插件版本，这个问题刚刚修了，之后会更新的。

好的
