### ISSUE TITLE
如何获取TTML格式歌词文件？

### ISSUE THREAD

**Issue by Bacon257** [Steve-xmh/applemusic-like-lyrics#107]
请问哪里可以下载TTML格式歌词文件？qq音乐和酷狗音乐使用的逐字歌词文件格式分别是lrc和krc。

**Comment by Steve-xmh** [comment]
目前有两种方式获取一个TTML歌词：
- 自己通过 Apple Music 网页版爬虫自行获取，有关这个的工具我还在做：https://github.com/Steve-xmh/amll-ttml-tool
- 在我自己建的 TTML 仓库里情愿你想要的歌的网易云音乐 ID（发个 Issue），我看看有没有兴趣去抓取歌词了：https://github.com/Steve-xmh/amll-ttml-db
- 看 Lyricify 作者愿不愿意公开自己的歌词数据库了，不过我想即便是公开了也不好拿过来用

**Comment by Doushabao233** [comment]
> 目前有三种方式获取一个TTML歌词：
> 
> * 通过我制作的 TTML 歌词编辑器来制作：https://github.com/Steve-xmh/amll-ttml-tool
> * 在我自己建的 TTML 仓库里请愿你想要的歌的网易云音乐 ID（发个 Issue），我看看有没有兴趣去抓取歌词了：https://github.com/Steve-xmh/amll-ttml-db
> * 看 Lyricify 作者愿不愿意公开自己的歌词数据库了，不过我想即便是公开了也不好拿过来用

话说QQ音乐这些平台不应该有TTML下载吗？就像LRC一样，难道不能直接爬取吗？

**Comment by Steve-xmh** [comment]
> > 目前有三种方式获取一个TTML歌词：
> > 
> > * 通过我制作的 TTML 歌词编辑器来制作：https://github.com/Steve-xmh/amll-ttml-tool
> > * 在我自己建的 TTML 仓库里请愿你想要的歌的网易云音乐 ID（发个 Issue），我看看有没有兴趣去抓取歌词了：https://github.com/Steve-xmh/amll-ttml-db
> > * 看 Lyricify 作者愿不愿意公开自己的歌词数据库了，不过我想即便是公开了也不好拿过来用
> 
> 话说QQ音乐这些平台不应该有TTML下载吗？就像LRC一样，难道不能直接爬取吗？

QQ音乐使用的是 QRC 格式歌词，是可以抓取，且通过我的歌词编辑工具都可以转换成 TTML 格式音乐，但是精确度不如人工打轴，而且并不包含 TTML 提供的高级歌词效果，所以不会考虑使用它们。
