### ISSUE TITLE
有可能实现手机端am的样式吗

### ISSUE THREAD

**Issue by 22Frederic** [Steve-xmh/applemusic-like-lyrics#108]
就像lyricify一样，这种窗口对日常使用更友好，而且在一定程度上可以减少性能占用
![屏幕截图 2023-04-02 131006](https://user-images.githubusercontent.com/105597335/229333343-3ce8abf0-e74b-48ff-b17c-7363b56229af.png)

**Comment by Steve-xmh** [comment]
会尝试考虑，不过你也可以通过隐藏所有播放信息来近乎实现只有纯粹的歌词窗口的效果

**Comment by 22Frederic** [comment]
主要是网易云对窗口最小大小有限制，没法拉成这样

**Comment by cale044** [comment]
感觉不错

**Comment by Steve-xmh** [comment]
开发版本已引入简单的样式，日后再磨
