### ISSUE TITLE
流体背景渲染效果无法在歌词页面开启

### ISSUE THREAD

**Issue by Bacon257** [Steve-xmh/applemusic-like-lyrics#109]
如题，在歌词页面右键打开“插件设置”菜单，选择“流体”效果，背景为全黑。
该效果只能在主界面的插件管理内开启。

**Comment by Steve-xmh** [comment]
这个是已知情况，切换背景效果的时候不会触发主题色重新计算，所以是默认全黑的。
在页面里切歌后就可以更新主题色了，之后再看看要不要修（毕竟不是很严重）

**Comment by Steve-xmh** [comment]
已修正
