### ISSUE TITLE
功能请求：歌词页面手动校正时间戳

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/applemusic-like-lyrics#11]
**功能描述**：有为数不少的歌曲的歌词时间戳差了那么半秒一秒的，安装插件以后就不能用自带的菜单来调节它了，这时候就需要一个按钮来纠正这些问题了
**对使用体验的影响**：一般

**Comment by Steve-xmh** [comment]
日后有空会另作工具来编辑网易云的歌词，到时候可以自己修改 AMLL 下载下来的歌词文件来矫正时间戳。
目前的话暂时可能不会去做这个东西，看我精力和心情吧

**Comment by Reinhardt-L** [comment]
好像在betterncm里面重载网易云之后会导致原本对准的歌词错开 点一下歌词跳转一下好像就好了

**Comment by Steve-xmh** [comment]
> 好像在betterncm里面重载网易云之后会导致原本对准的歌词错开 点一下歌词跳转一下好像就好了

插件是通过监听网易云 Cpp 端发来的进度事件来同步进度的，然后最离谱的是它传过来的播放进度单位是秒，小数点还有误差（

所以会产生一定的精度问题且不好修正（多出现在中途播放歌词的情况下）

**Comment by kikozz** [comment]
+1
如果启用UnblockNeteaseMusic插件，部分歌曲会因为此插件出现歌词对不上的情况。
所以很需要这个歌词时间戳手动校准。

**Comment by Steve-xmh** [comment]
已支持全局时间轴调节，针对歌词的时间轴调节之后会提供

**Comment by Steve-xmh** [comment]
已支持全局+单个歌曲的时间轴条件，将在下一个版本提供

<img width="1407" alt="截屏2023-02-06 13 52 34" src="https://user-images.githubusercontent.com/39523898/216893985-f3b761b0-5d78-4576-9c23-3b257685ee55.png">

<img width="1407" alt="截屏2023-02-06 13 52 21" src="https://user-images.githubusercontent.com/39523898/216893963-50210cc6-b865-4965-a115-2aba4dcf6f85.png">
