### ISSUE TITLE
更换分支后更新异常

### ISSUE THREAD

**Issue by raindropQWQ** [Steve-xmh/applemusic-like-lyrics#113]
在商店中下载非beta版AMLL后，在插件内设置中选择2.0beta分支，此时可以正常更新到beta版
但之后如果beta版有更新，在插件内设置中点击更新，网易云重启完成后会发现插件并没有更新

此时可以删除插件，然后重新在商店中下载非beta版，再更换分支并更新到最新版

**Comment by Steve-xmh** [comment]
之后很快就会合并正式版本，分支问题会在正式版后处理
