### ISSUE TITLE
2.0.0正式稳定版安装后歌词界面报错

### ISSUE THREAD

**Issue by Bacon257** [Steve-xmh/applemusic-like-lyrics#115]
![QQ截图20230408183157](https://user-images.githubusercontent.com/100892568/230716495-adf6838a-806b-4071-be44-46216ec0419e.png)
![QQ截图20230408183243](https://user-images.githubusercontent.com/100892568/230716518-596bd2ae-a5fa-49ab-a3ad-f84e2e07c4c9.png)

**Comment by Steve-xmh** [comment]
请卸载 LibFrontendPlay 插件或换用 MRBNCM 插件加载器

**Comment by Bacon257** [comment]
可能是之前卸载插件时出了点问题，我截这两张图时插件界面里已经没有LibFrontendPlay了还是会报错。
最后把betterncm整个重装了一遍才好了..
