### ISSUE TITLE
增加歌词字体渲染精度分辨率

### ISSUE THREAD

**Issue by floatanddream** [Steve-xmh/applemusic-like-lyrics#116]
![image](https://user-images.githubusercontent.com/53161114/230717234-4325d9ea-191d-46ae-9476-8db2c8a11c38.png)

开启全屏时，歌词字体渲染字体会比较模糊。
建议添加一个可调节的比率，就像背景渲染精度一样。

**Comment by Steve-xmh** [comment]
看上去没问题呀，字这个样子很正常呀

**Comment by floatanddream** [comment]
> 看上去没问题呀，字这个样子很正常呀

可能我比较emmm追求完美，但是我就感觉字体的描边有点模糊的感觉

**Comment by Steve-xmh** [comment]
> > 看上去没问题呀，字这个样子很正常呀
> 
> 可能我比较emmm追求完美，但是我就感觉字体的描边有点模糊的感觉

可能是 Chrome 的位移产生的抗锯齿模糊吧，这个我也不好去修，之后再看看能不能优化吧。
