### ISSUE TITLE
插件和 Material You 主题插件合用时有布局问题

### ISSUE THREAD

**Issue by github-tang** [Steve-xmh/applemusic-like-lyrics#117]
非全屏：

https://user-images.githubusercontent.com/88638584/230726198-ac8eca5a-9e52-4e4d-b618-6a4604ff5f5e.mp4

全屏：

https://user-images.githubusercontent.com/88638584/230726210-e1630e2e-7114-4480-9e14-df3ca7f66207.mp4

全屏下似乎有一部分被任务栏遮挡了，应该是窗口比例的问题。

全过程：

https://user-images.githubusercontent.com/88638584/230726380-a6a668cb-1cec-4593-95de-f66537765f08.mp4

**Comment by Steve-xmh** [comment]
看情况你应该是使用了自定义任务栏的插件，加上网易云的全屏是窗口全屏而非真正意义上的全屏，导致你任务栏将网易云的窗口遮盖了。
这个应该不是 AMLL 插件的问题，如果移除了你的自定义任务栏插件后问题仍然存在的话，建议截图或录制一个全屏幕的效果出来。

**Comment by github-tang** [comment]
https://user-images.githubusercontent.com/88638584/230727696-11b5ae87-7cd6-4720-90b9-037913c5477f.mp4

**Comment by Steve-xmh** [comment]
看出来了，这个有可能是主题干扰，之后我再看看要不要做兼容吧

**Comment by Steve-xmh** [comment]
开发版本里已经修好了（至少我这里使用 Material You 中不会产生布局问题了）
