### ISSUE TITLE
播放页下方功能区过渡不太好（不如RNP）

### ISSUE THREAD

**Issue by Reinhardt-L** [Steve-xmh/applemusic-like-lyrics#12]
同时安装RNP和您这个插件的下方功能栏是这样的
![image](https://user-images.githubusercontent.com/65754243/211451433-b86efa83-9f2a-4862-8cac-20cee8f05a15.png)
删了之后是这样的
![image](https://user-images.githubusercontent.com/65754243/211451551-59d63652-0bc6-45c3-b4e4-fd582060b298.png)
可以做下支持吗（？

**Comment by Steve-xmh** [comment]
插件只修改播放的主要页面，播放栏部分是不动的（降低与主题插件的不兼容）
可以使用其他主题插件来修改这部分的样式
