### ISSUE TITLE
一个界面显示的bug

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/applemusic-like-lyrics#121]
***正在使用dev-0.04***
### bug描述：
此bug发生时，会在正在播放界面上同时显示半屏歌词和半屏评论，且无法正常滑动页面
### 如何复现：
正常播放一首歌曲，打开歌词页面，下拉到半屏歌词与半屏评论的状态，点击“私人FM”
### 截图：
[
![QQ截图20230410222215](https://user-images.githubusercontent.com/50747104/230921510-548e20ee-65de-4d20-b88d-476c06541964.png)
](url)

**Comment by Steve-xmh** [comment]
已更新到 v2.1.6，自测没有这样的布局问题出现了，所以先关掉了
