### ISSUE TITLE
歌词行在行数过多时间隔错误

### ISSUE THREAD

**Issue by 22Frederic** [Steve-xmh/applemusic-like-lyrics#124]
目前只有这一首歌会这样
![屏幕截图 2023-04-14 225715](https://user-images.githubusercontent.com/105597335/232085757-6262dd25-f5c1-47dd-88d8-5466fac7386d.png)

**Comment by Steve-xmh** [comment]
不太明白意思，是歌词行间间距不一样吗

**Comment by 22Frederic** [comment]
是的，也许是行数太多了？

**Comment by Steve-xmh** [comment]
已优化，应该没有问题了
