### ISSUE TITLE
【增强】希望能在保存的json歌词缓存中加入歌曲信息

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/applemusic-like-lyrics#126]
最近在做一个适配新版本eslyric（FB2K的歌词插件）的逐字歌词转换脚本，为了偷懒，数据源用的是amll的缓存，但是缓存的json文件里不一定有歌曲信息，自己找api或者搭建api成本又有点高，所以希望dalao能给缓存里加上歌曲信息，谢谢

**Comment by Steve-xmh** [comment]
你可以提一个字段来存你需要的歌词信息
我会考虑做读取的支持

**Comment by Xionghaizi001** [comment]
比如“TrackInfo” ？只需要歌名和歌手就好，谢谢dalao

**Comment by Steve-xmh** [comment]
v2.1.7 已增加
