### ISSUE TITLE
有没有可能救一救屏蔽词😂

### ISSUE THREAD

**Issue by 22Frederic** [Steve-xmh/applemusic-like-lyrics#127]
如图，不知道网易云对“fuck”这个词这么执着，都加星号屏蔽也太难受了，但am都直接显示的，能使它正常显示吗
![屏幕截图 2023-04-15 223248](https://user-images.githubusercontent.com/105597335/232234488-77fdbb42-ddf5-4ff6-803b-e56c1d93936c.png)
![屏幕截图 2023-04-15 223342](https://user-images.githubusercontent.com/105597335/232234492-108fa533-70e6-4622-80e9-b691d41fa26c.png)

**Comment by Steve-xmh** [comment]
获取到的歌词是什么样的，就会显示成什么
你只能通过修改对应的歌词缓存文件来修改原文歌词
