### ISSUE TITLE
希望能添加使用自定义字体功能

### ISSUE THREAD

**Issue by RuriAlpha** [Steve-xmh/applemusic-like-lyrics#129]
在电脑上正确安装了Pingfang_SC和SF Pro字体，但是插件似乎无法正确识别并使用它们，建议添加一个使用自定义字体的功能，这样至少能在他没法正确识别苹方和SF Pro的时候使用自己已经装好的字体www
<img width="767" alt="image" src="https://user-images.githubusercontent.com/40235755/232469065-16f7e08f-c5e1-4cd4-8619-2d44606ab499.png">

**Comment by Steve-xmh** [comment]
安装完字体后需要重启网易云方可生效，我的想法是有插件干扰了播放页面的字体，请自行检查一下自己所用的插件中是否有能够修改字体的插件，如果有的话可以使用其他插件来修改字体

**Comment by RuriAlpha** [comment]
> 安装完字体后需要重启网易云方可生效，我的想法是有插件干扰了播放页面的字体，请自行检查一下自己所用的插件中是否有能够修改字体的插件，如果有的话可以使用其他插件来修改字体

已通过使用TinyNCM更改全局字体的方式解决
