### ISSUE TITLE
一个离谱的歌词分行bug

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/applemusic-like-lyrics#130]
_正在使用dev-2.0.2_

**bug描述：**
有些歌的歌词把翻译行作为背景对白展示，然后就出现了这个bug

**bug表现：**
如图
![111](https://user-images.githubusercontent.com/50747104/233371481-1db372df-6f23-4976-863b-47106250eb5e.png)

**Comment by Xionghaizi001** [comment]
试了一下，开了逐字歌词就会出这个bug，不开就不会，你刚才说的替换id的方法也试过了

**Comment by Steve-xmh** [comment]
因为不能复现，所以暂时关闭该议题
