### ISSUE TITLE
GPU占用率极高

### ISSUE THREAD

**Issue by lamberve** [Steve-xmh/applemusic-like-lyrics#131]
版本是2.0.2，更新到此版本后，GPU占用率极高，之前没有过

**Comment by lamberve** [comment]
打开歌词页面GPU占用率达到90，关闭歌词页占用率就下来了

**Comment by Steve-xmh** [comment]
问题很奇特，尝试重启网易云吧。
如果是和资源占用相关的Issue，请补充一下电脑配置信息。
AMLL的最低显卡配置（个人认为）是 GTX 1050 及以上，如果太低配置的话会非常卡顿
而且网易云本身对 CEF 框架的使用就很迷，会有意义不明的性能 Bug 是我没办法复现的。

**Comment by lamberve** [comment]
作者你好，我的显卡是RTX 3060，配置应该是够的。问题主要是这次更新后出现的，如果没法复现的话就算了，感谢
