### ISSUE TITLE
歌词辉光建议

### ISSUE THREAD

**Issue by Y-CIAO** [Steve-xmh/applemusic-like-lyrics#135]
可以增加中间长时间歌词的辉光吗，Lyricify4.0也有这个功能，隔壁的另一个网易云也有这个功能，只是他的辉光效果没你的好。还有就是中文歌词可以增加辉光吗？目前看好像只支持英语。

**Comment by Steve-xmh** [comment]
似乎没有遇到中文会发光的歌词效果，能举个例子吗（AM里有这种中文发光效果的歌）

**Comment by Y-CIAO** [comment]
应该没有，只是我的一个建议。就是如果那个词持续时间很长，可以增加发光。但好像不好识别词语，只能一个字是吧？

**Comment by Steve-xmh** [comment]
> 应该没有，只是我的一个建议。就是如果那个词持续时间很长，可以增加发光。但好像不好识别词语，只能一个字是吧？

是这样，中文不太方便做拆词和播放时长的判断，英语的话我只是刻意只允许最后一个单词发光的，之后会给一个设置让中间长时间的英语单词也能发光。

**Comment by Xionghaizi001** [comment]
> > 应该没有，只是我的一个建议。就是如果那个词持续时间很长，可以增加发光。但好像不好识别词语，只能一个字是吧？
> 
> 是这样，中文不太方便做拆词和播放时长的判断，英语的话我只是刻意只允许最后一个单词发光的，之后会给一个设置让中间长时间的英语单词也能发光。


或许可以做一个时间差值判断，大于本句中的平均时间差值就视为长音字/词，就应用辉光效果

**Comment by Steve-xmh** [comment]
目前开发版本已经允许所有时长大于等于1秒的英文单词应用辉光效果，中文词汇难度较大就暂时先不做了
