### ISSUE TITLE
【增强】专辑图片背景色彩渐变不平滑

### ISSUE THREAD

**Issue by Bacon257** [Steve-xmh/applemusic-like-lyrics#138]
专辑图片背景的色彩渐变有一圈圈的纹路，有点影响观感。希望调整一下。
![QQ截图20230530102504](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/100892568/ee80a360-2038-4b54-81e8-4e5bcc4ae0e6)

**Comment by Steve-xmh** [comment]
这个和浏览器框架对高斯模糊的处理有关，这个就不是我能修的了（
你可以尝试一下在 Photoshop 里用渐变工具，关闭仿色选项填充一个，效果也是一样的
不过如果打开了仿色就会通过增加噪点实现相对舒服的过渡，不知道这个浏览器能不能做到（

关闭了仿色后做的填充：
<img width="1582" alt="image" src="https://github.com/Steve-xmh/applemusic-like-lyrics/assets/39523898/49881d1a-1844-4706-8c58-9da1af37fe02">


打开了仿色后做的填充：
<img width="1582" alt="截屏2023-05-30 10 39 35" src="https://github.com/Steve-xmh/applemusic-like-lyrics/assets/39523898/28e79347-8c12-43b5-8c92-1137246ec6b8">

**Comment by Steve-xmh** [comment]
确认了一下，这个现象叫做色带现象（Color Band），对于目前的浏览器来说确实不太好优化这个效果。
等之后我优化WebGL系背景加上颜色抖动吧（Color Dithering）

**Comment by Bacon257** [comment]
了解了
