### ISSUE TITLE
显卡占用超高

### ISSUE THREAD

**Issue by Sn0r1axi** [Steve-xmh/applemusic-like-lyrics#139]
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/26668216/7492cdb6-fbcf-40d1-b90b-f5c543e6c9a7)
使用最新版本，打开歌词页面占用率飙升，应该不是正常情况吧。

**Comment by Steve-xmh** [comment]
确实是正常情况（尤其是如果你的效果开得多的话）
目前基准是 M2 8核下占用会近乎饱和，我的 3090 占用也有 20% 左右，看了一下你的显卡，性能上大概也是我的显卡的四分之一，所以这个占用也比较正常
性能优化可以尝试禁用歌词行模糊效果和缩放，这两个占用会多一些，其他的可以自行微调
