### ISSUE TITLE
无歌词段的三点字体过大，大小无法自定义

### ISSUE THREAD

**Issue by Rothes** [Steve-xmh/applemusic-like-lyrics#14]
![Rothes-ScreenShot_230111-182734](https://user-images.githubusercontent.com/47097395/211782882-bac3c32e-742b-4365-a26e-8994860e1cbb.gif)
歌词字体大小为13像素

希望添加设置或自优化大小

**Comment by Steve-xmh** [comment]
已增加和自定义字体大小同步的功能
