### ISSUE TITLE
dev分支的bug

### ISSUE THREAD

**Issue by ITManCHINA** [Steve-xmh/applemusic-like-lyrics#141]
刚更新完的dev分支会导致BetterNCM 1.2.1无法启用AMLL插件，bncm的设置里面会变灰

**Comment by Steve-xmh** [comment]
dev 分支正在做对网易云 3.0.0 的实验性支持，可能会对目前的正式版本网易云产生影响，之后会修的

**Comment by ITManCHINA** [comment]
> dev 分支正在做对网易云 3.0.0 的实验性支持，可能会对目前的正式版本网易云产生影响，之后会修的

明白了，在此感谢您优秀的作品

**Comment by Steve-xmh** [comment]
2.1.0 已更新
