### ISSUE TITLE
【BUG】播放页面不显示设置的背景

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/applemusic-like-lyrics#143]
_使用版本：dev 2.1.0_
如图，播放页面没有正确显示设置的效果（设置了流体效果）
![QQ截图20230617234420](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/50747104/897781cc-449f-47d3-81d9-972b9e897f27)

**Comment by Steve-xmh** [comment]
dev 分支正在做对网易云 3.0.0 的实验性支持，可能会对目前的正式版本网易云产生影响，之后会修的

**Comment by Xionghaizi001** [comment]
所以在哪里可以找到历史版本😂我想回退到上一个版本 ，这个版本不仅播放页面有问题而且似乎还引起了不能正常播放的bug

**Comment by Steve-xmh** [comment]
> 所以在哪里可以找到历史版本😂我想回退到上一个dev版本 ，这个版本不仅播放页面有问题而且似乎还引起了不能正常播放的bug

无法回滚开发版本，只能重新安装正式版本。
毕竟是开发版本，需要用户自行承担使用产生大量问题的后果。

**Comment by Steve-xmh** [comment]
2.1.0 已更新
