### ISSUE TITLE
在新版网易云中无法获取歌词

### ISSUE THREAD

**Issue by 22Frederic** [Steve-xmh/applemusic-like-lyrics#145]
旧版网易云是正常的，但是到了新版就无法获取歌词了，是我哪里操作不正确吗
![屏幕截图 2023-06-24 014604](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/105597335/289d8f6e-dad7-4bef-beff-ef728c7b8a1f)
![屏幕截图 2023-06-24 014714](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/105597335/c43013e1-cfc7-4831-9e96-021b016b79d7)

**Comment by Steve-xmh** [comment]
2.1.2 应该更新修复了
