### ISSUE TITLE
歌词显示问题

### ISSUE THREAD

**Issue by floatanddream** [Steve-xmh/applemusic-like-lyrics#146]
https://github.com/Steve-xmh/applemusic-like-lyrics/assets/53161114/3a73d1be-f34a-4822-9aa0-e9b3910f6315

正在播放时如果通过点击歌词调整播放时间位置时，就会出现视频这样子的bug。不会显示接下来的歌词。

**Comment by Steve-xmh** [comment]
2.1.3 已修正
