### ISSUE TITLE
2.1.2 不能正常播放

### ISSUE THREAD

**Issue by ZhangEnlin** [Steve-xmh/applemusic-like-lyrics#147]
更新到2.1.2之后不能更改背景，而且只有首次打开应用可以正常播放音乐，下一首就不能正常播放了

**Comment by Steve-xmh** [comment]
关于背景，还在移植，请耐心等待：
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/39523898/917849b3-08e2-464d-bee7-2eb0fb2c9ab1)
关于音乐播放，请提供一下你的网易云版本号，我排查一下原因。

**Comment by ZhangEnlin** [comment]
> 关于背景，还在移植，请耐心等待： ![image](https://user-images.githubusercontent.com/39523898/248450748-917849b3-08e2-464d-bee7-2eb0fb2c9ab1.png) 关于音乐播放，请提供一下你的网易云版本号，我排查一下原因。

版本：2.10.8（Build:200945)

**Comment by Steve-xmh** [comment]
v2.1.4 已修复
