### ISSUE TITLE
[BUG]私人FM页面歌词渲染错乱

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/applemusic-like-lyrics#150]
BUG表现如图，涉及版本包括2.1.2、2.1.3、2.1.4、截至发帖时最近的2个dev分支版本
![QQ截图20230624191025](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/50747104/5fc59d78-fb65-4027-b754-69ec218e33f7)

**Comment by Steve-xmh** [comment]
v2.1.5 已修正
