### ISSUE TITLE
[BUG]私人FM评论加载不出字而且打开了评论区就不能拉回歌词页

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/applemusic-like-lyrics#151]
_正在使用2.1.5版本_
BUG表现如图
（刚才发错图了
![QQ截图20230624194739](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/50747104/2b6c266c-fd78-4f38-a042-703ac8ffcb33)

**Comment by Steve-xmh** [comment]
v2.1.6 已修正
