### ISSUE TITLE
【增强】希望给苹果系字体下载链接换源

### ISSUE THREAD

**Issue by HIBIKl** [Steve-xmh/applemusic-like-lyrics#155]
现在的会直接下载整个字体仓库，下载时间长，而且里面的ttc字体不适配windows，无法简单地直接安装

**Comment by Steve-xmh** [comment]
能提供一个长期有效的下载直链吗

**Comment by HIBIKl** [comment]
自己整理的字体，放到了OneDrive里面：
https://1drv.ms/f/s!Anmx7jZgAR8sr0TgWqv-FqMWtzaG?e=DboZ38

**Comment by Steve-xmh** [comment]
字体源在开发版本已更换，非常感谢！
