### ISSUE TITLE
【重构计划】将播放页面组件完全独立出来并成为独立组件库

### ISSUE THREAD

**Issue by Steve-xmh** [Steve-xmh/applemusic-like-lyrics#156]
此计划目的在于让更多基于 React/Vue(加装胶水层的情况) 开发的音乐播放器使用目前 Web 上对苹果歌词效果模仿最好的播放组件，实现大家对歌词显示的质的提升。

重构进度：
- [x] 重构背景组件
- [x] 重构歌词显示组件
  - [x] 基本歌词显示
  - [x] 单词辉光效果
  - [x] 间奏三点动画效果
- [x] 重构 React 绑定
- [x] #196
- [x] 开发 Vue 绑定

**Comment by Steve-xmh** [comment]
好像 Jotai 状态库是允许多个提供器存在的，那我想可以保留，不需要做太多的修改。

**Comment by TalexDreamSoul** [comment]
可以考虑做成纯js的?? 避免强绑定框架，或者可以抽离逻辑和UI
做成
- apple-music-like-lyrics/core
- apple-music-like-lyrics/react
- apple-music-like-lyrics/vue
- .....

**Comment by cale044** [comment]
你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。

**Comment by Steve-xmh** [comment]
> 可以考虑做成纯js的?? 避免强绑定框架，或者可以抽离逻辑和UI 做成
> 
> * apple-music-like-lyrics/core
> * apple-music-like-lyrics/react
> * apple-music-like-lyrics/vue
> * .....

可能工作量会有所增加（）
但是不失为一种办法，就是得好好分清楚分工才行（

**Comment by Steve-xmh** [comment]
核心组件的所有基本功能特性均已基本完成，并且测试了性能，在十年前的 Intel Pentium G2020 和其集成显卡运行上能够有 15-25 FPS 之间的帧数（分辨率在 1280x1024 左右），关闭背景动画则可以提高到 20-30 FPS。
接下来开始编写 React 绑定，准备和网易云插件进行对接

**Comment by Steve-xmh** [comment]
重构基本完成
