### ISSUE TITLE
【BUG】私人FM播放歌曲和工具栏显示的不是同一首歌

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/applemusic-like-lyrics#157]
_正在使用2.1.5_
【BUG描述】
点击私人FM并正常播放，自动切换至下一曲或者几首歌曲后，实际播放的歌曲与工具栏显示的歌曲名不一样。
此时点击暂停再播放会播放进入私人FM前播放的歌曲，点击左下角专辑图标进入播放页面显示的是错误的歌曲信息和歌词。
【临时解决办法】
手动点进私人FM页面即可刷新
【影响范围】
正式版2.1.2至今
最近2-3个内测版
【截图】
没有截图
【复现成功率】
接近100%

**Comment by Steve-xmh** [comment]
能提供网易云版本号吗

**Comment by Xionghaizi001** [comment]
> 能提供网易云版本号吗

2.10.6 (Build:200601)(Patch:1:aa07988)
