### ISSUE TITLE
建议减少PixiJS黑色的权重

### ISSUE THREAD

**Issue by floatanddream** [Steve-xmh/applemusic-like-lyrics#158]
![7d3157227f2b690b7a6d34fd96d2c65](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/53161114/e5f2abfe-1fee-45fd-a16e-ececfbc06ef8)

在播放某些歌曲封面背景为大多部分为暗色的情况下，整个绘制会变成黑色。

**Comment by Steve-xmh** [comment]
开发版本中已优化
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/39523898/00e599e6-ae04-4078-8e1c-9d0c39d69e55)
