### ISSUE TITLE
歌词结尾创作者存在歧义

### ISSUE THREAD

**Issue by CalCobalt** [Steve-xmh/applemusic-like-lyrics#159]
歌曲创作者和歌词贡献者混到一起了

![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/96706505/322eee0e-3197-418b-b88b-5d0cb0641014)

**Comment by Steve-xmh** [comment]
有人觉得多两行歌词贡献者会哗众取宠，有人觉得合并起来会混淆
就挺纠结的

**Comment by CalCobalt** [comment]
> 有人觉得多两行歌词贡献者会哗众取宠，有人觉得合并起来会混淆 就挺纠结的

歌词贡献者毕竟不是创作者啊……

**Comment by Steve-xmh** [comment]
> 
> 
> 
> > 有人觉得多两行歌词贡献者会哗众取宠，有人觉得合并起来会混淆 就挺纠结的
> 
> 歌词贡献者毕竟不是创作者啊……

毕竟歌词分两种，原文歌词和翻译歌词，多两行被人说，少两行也被说
之后我有空加选项配置这个的形式吧
