### ISSUE TITLE
关于安装AMLL之后侧边栏和歌单部分内容会被播放状态栏遮挡

### ISSUE THREAD

**Issue by feng-or** [Steve-xmh/applemusic-like-lyrics#16]
![image](https://user-images.githubusercontent.com/104701550/211822134-a377f1cd-ccf8-4cb8-81b2-9eb3342feca7.png)
此图为装插件的情况
![image](https://user-images.githubusercontent.com/104701550/211822854-9798d7fd-58df-4962-af2f-0b1081a3faa2.png)
此图为删掉插件之后
在插件设置页面中也有相同的情况（滚动条已拉到底）（需要将窗口放大后才能查看部分内容）
![image](https://user-images.githubusercontent.com/104701550/211823672-4bd2b5fa-1423-4d1b-93b0-d97fa305e035.png)
![image](https://user-images.githubusercontent.com/104701550/211823420-6a358683-bcf6-4234-b47b-a014c34ff79a.png)
插件版本为1.5.1

**Comment by Steve-xmh** [comment]
和 #15 一样
