### ISSUE TITLE
关于歌曲间奏动画问题

### ISSUE THREAD

**Issue by HaoZi9167** [Steve-xmh/applemusic-like-lyrics#160]
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/10b008c8-cdff-4fe4-ac34-56d3f0bd610f)
歌曲间奏呼吸动效存在排版问题 相较于歌词较为靠下
且在消失过程中极有可能被下一句歌词动画打断而直接消失

https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/004e18fd-266b-4a02-b660-95695217cca7

建议仿照apple music
在下一句歌词出现时强制提前播放呼吸动画的消失动画以确保流畅性

https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/5322166a-bdc3-4d8d-bbe6-0af003863399

**Comment by Steve-xmh** [comment]
之前为了确保流畅性就只使用了 Web Animation API 来实现三点动画，之后发现如果时间一长就会有时间误差导致动画有误。
之后有空会重构成 requestAnimationFrame 的形式，应该能从根本上解决问题。
