### ISSUE TITLE
【bug】播放控制界面按钮问题

### ISSUE THREAD

**Issue by HaoZi9167** [Steve-xmh/applemusic-like-lyrics#161]
点击专辑下方的“切换播放模式”按钮并切换至列表循环后将无法再点击，必须退出播放界面并使用网易云自带控制组件进行切换
且当播放“我喜欢的音乐”歌单时，通过AMLL切换的“列表循环”模式实际上是心动模式
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/97431d01-956e-4054-8e5e-df8e93ad3fef)
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/eb8e9da4-3954-44bd-bbb1-b82a616a24fe)

**Comment by HaoZi9167** [comment]
目前发现只在网易云3.0版本中存在该问题，2.x版本正常

**Comment by Steve-xmh** [comment]
> 目前发现只在网易云3.0版本中存在该问题，2.x版本正常

网易云 3.0.0 现在有心动模式了吗（？）
我好像还没推送更新，有安装包吗

**Comment by HaoZi9167** [comment]
实际上是有的
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/e750e78e-0cca-40d1-a8b7-8afab3b21eb3)
官网下载不知道怎么回事不见了 这个是我当时的下载链接
https://d1.music.126.net/dmusic/NeteaseCloudMusic_Music_official_3.0.1.201499_64.exe

**Comment by Steve-xmh** [comment]
> 实际上是有的 ![image](https://user-images.githubusercontent.com/138546084/251605766-e750e78e-0cca-40d1-a8b7-8afab3b21eb3.png) 官网下载不知道怎么回事不见了 这个是我当时的下载链接 https://d1.music.126.net/dmusic/NeteaseCloudMusic_Music_official_3.0.1.201499_64.exe

神奇的网易云操作动线.jpg
AMLL 是通过模拟点击这些按钮来实现切换播放模式的，因为之前点击的时候没点出心动模式所以就只写了那几个播放模式的操作，后面有空补充上吧。
