### ISSUE TITLE
版本不兼容出错，重载重装都没用

### ISSUE THREAD

**Issue by qr-kk** [Steve-xmh/applemusic-like-lyrics#164]
#错误；
问题描述：插件页面显示版本不兼容，加载不出来，
- 网易云版本：2.10.11
- 插件1.2.1

问题截图：
<img width="767" alt="微信图片_20230707163348" src="https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138861317/3c3d3b41-08ac-4635-b7d8-3f2fa82f00a4">

**Comment by Steve-xmh** [comment]
请前往 [BetterNCM](https://github.com/MicroCBer/BetterNCM) 本家仓库提交错误
这个不是 AMLL 插件的问题
