### ISSUE TITLE
歌词英文显示问题

### ISSUE THREAD

**Issue by 22Frederic** [Steve-xmh/applemusic-like-lyrics#167]
使用SF Pro，歌词播放时字母“J”显示不全，未播放时正常
![屏幕截图 2023-07-10 180943](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/105597335/c71bb15b-e53c-4da9-8777-dd64550dc06a)
![屏幕截图 2023-07-10 180954](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/105597335/442478d6-5d4e-495f-8d95-a908d3658def)

**Comment by Steve-xmh** [comment]
~~天，这都能看出来~~

有空确认一下怎么修

**Comment by Steve-xmh** [comment]
查询了一下，这个是已知问题，目前 CSS4 好像有一个 `text-space-collapse` 样式草案能够修正这个问题。
但是没有任何浏览器提供支持，所以很遗憾没办法修。
如果删除对这些单词的 `inline-block` 的话虽然可以恢复正常字形，但是会导致无法应用任何效果（悬浮、渐变、辉光等）

相关链接：https://stackoverflow.com/a/5078350
如果以后与此类似的样式属性能够出现的话就尽快修正这个问题，故先关闭了。
