### ISSUE TITLE
歌词辉光动画问题

### ISSUE THREAD

**Issue by HaoZi9167** [Steve-xmh/applemusic-like-lyrics#168]
众所周知逐词动画中的每一个字都会在唱到的时候微微上浮（划去
如果一句歌词里有辉光歌词，且这句话刚好唱完时
这句歌词的消失动画中 辉光歌词会呈现出没有上浮的状态

https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/87c311b0-cbb1-4c6e-aa27-96a3035161d7

（比如上面这个reflection明显突然往下降了一点）

**Comment by HaoZi9167** [comment]
发现了一点 好像和上浮没有什么关系... 好像辉光动画本来就会比一般的歌词高一点

**Comment by Steve-xmh** [comment]
性能做出的妥协（）
因为这个玩意性能开销很大，所以辉光效果用的是纯 CSS 实现的，表现力尚有瑕疵
之后我看看能用什么办法来缓解吧

**Comment by HaoZi9167** [comment]
顺便问一下大佬
最近dev版本的背景取色是改过了吗
感觉变亮了好多（）黑色的面积变少了

**Comment by Steve-xmh** [comment]
是这样的，参见 https://github.com/Steve-xmh/applemusic-like-lyrics/issues/158

**Comment by Steve-xmh** [comment]
开发版本已优化，可能在点击歌词跳转的时候出现瑕疵，日后修缮。
