### ISSUE TITLE
在全屏模式下边角仍然可拖拽且存在圆角以及建议

### ISSUE THREAD

**Issue by Adentent** [Steve-xmh/applemusic-like-lyrics#169]
如题。
![图片](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/96329894/9c57d5c7-2b1b-425a-a7ac-1f4e6395ef9b)

不建议将常用功能全部堆放在歌词的…界面当中，是否可以截选一些直接放在歌词界面当中？例如喜欢歌词和全屏界面等等，或者提供配置项。反而听歌识曲这样没大用处的东西却出现在了歌词界面右上角。以及希望能提供一定时间内未移动鼠标时隐藏鼠标的功能，提高美观程度，更上一层楼地，在长时间不移动鼠标时，隐藏音量条、退出按钮、…按钮、右上角功能按键等等来提供更好的观感，虽然可能有点脱离了Apple Music闭门造车，但毕竟也可以提高观感ww

感谢阅读

**Comment by Adentent** [comment]
甚至在全屏之后将鼠标放在边角依然可以拖拽窗口，感觉不像是纯正的全屏而是让窗口占据了整个屏幕（逃

**Comment by Adentent** [comment]
并且在全屏/最大化状态下依然是不能完全覆盖屏幕，这一点在后方窗口打开了白色界面的情况下会更加明显：
![图片](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/96329894/dc67644e-24da-47c5-b6d1-748559bae612)

**Comment by Steve-xmh** [comment]
关于全屏，这个受制于网易云自己的CEF嵌入方式，没有办法修正去
不过全屏的圆角可以联系 BetterNCM 插件加载器作者来提供帮助来清除，不过这就不是我的插件的维护范围了
然后隐藏歌词组件的想法，可以考虑，请另外发一个议题来写这个吧
（这个议题就先关闭了，发议题前请参考置顶议题）
