### ISSUE TITLE
辉光歌词在开发版本的另一个新问题

### ISSUE THREAD

**Issue by HaoZi9167** [Steve-xmh/applemusic-like-lyrics#173]
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/2eda796a-c447-4279-8d5c-2d401b772c1e)
在没有播放的时候辉光歌词和别的歌词透明度不一样

**Comment by HaoZi9167** [comment]
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/2d906d38-a62e-4420-b77b-62a418d8057a)
触发条件还蛮玄幻的 好像是要歌词唱过一遍再倒退回去才会有问题
还有可能出现上图的样子

**Comment by HaoZi9167** [comment]
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/c48f5f4c-a3d0-473e-beed-414c5ef9aae6)
hai'hui还会出现这样的问题...

**Comment by Steve-xmh** [comment]
已知问题

**Comment by Steve-xmh** [comment]
现在应该修好了（吧）

**Comment by HaoZi9167** [comment]
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/31dbcaa7-4cc0-4477-94a1-c7c4aee9a2f9)
geng'yi更新以后问题依然在 评价是不急 不是什么大问题
