### ISSUE TITLE
[BUG]只有部分歌词具有翻译时歌词布局异常

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/applemusic-like-lyrics#179]
bug表现：
对于某些只有部分句子带有翻译的歌曲，插件会将所有歌词的句子显示成一团。通过其他方式（如网易云自带桌面歌词或者RuLyrics等其他插件）查看歌词，其表现是正常的

复现成功率：
对于某些歌曲必现，如
https://music.163.com/song?id=1824454151

截图：
![QQ截图20230720173114](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/50747104/eef67326-a622-4491-9dbc-0b4b6cf420a3)

环境信息：
插件版本   2.1.7
网易云      2.10.6 (Build：200601) (Patch：1:aa07988)
NCM管理器    1.2.1

**Comment by Xionghaizi001** [comment]
关联issue #130

**Comment by Steve-xmh** [comment]
https://github.com/Steve-xmh/applemusic-like-lyrics/issues/153#issuecomment-1607253308
