### ISSUE TITLE
[bug]插件似乎导致网易云其它页面无法滚动到底部

### ISSUE THREAD

**Issue by hv0905** [Steve-xmh/applemusic-like-lyrics#18]
如题，安装插件后会导致网易云歌单页面（和其它页面）底部内容显示不全：
![image](https://user-images.githubusercontent.com/29349119/212078592-9d369dbd-2f51-4457-acd1-2febc583b119.png)

通过F12调试后，发现有一段css将为底部预留margin的css覆盖了,将其删除就会恢复正常：
![image](https://user-images.githubusercontent.com/29349119/212078938-fabd8c0c-c895-42c7-be8f-1c13f2920c41.png)

而这段css来源于id为`apple-music-like-lyrics-style`的style block中

**Comment by Steve-xmh** [comment]
#15

**Comment by hv0905** [comment]
emm更新到1.5.2之后歌词列表好像在某些情况下不会滚动，点击歌词也不会跳转到对应的时间点，我还没找到稳定的复现方式。
我安装的插件列表：
![image](https://user-images.githubusercontent.com/29349119/212101547-31b1e91e-f435-4cab-af65-97b9bff5707d.png)
