### ISSUE TITLE
dev分支逐词歌词帧率低下

### ISSUE THREAD

**Issue by floatanddream** [Steve-xmh/applemusic-like-lyrics#181]
https://github.com/Steve-xmh/applemusic-like-lyrics/assets/53161114/e4064961-2447-463a-982c-cbbddff40b85

dev分支的逐词歌词帧率肉眼可见的连30帧都没有。

**Comment by Steve-xmh** [comment]
帧率较低没有办法，需要性能较好的电脑工作才会流畅
之后会尽可能优化性能，在那之前先忍耐一下吧
（因为不是什么特别要命的问题所以先关闭了）

**Comment by floatanddream** [comment]
> 帧率较低没有办法，需要性能较好的电脑工作才会流畅
> 之后会尽可能优化性能，在那之前先忍耐一下吧
> （因为不是什么特别要命的问题所以先关闭了）

CPU是i7-11800H
显卡是rtx3070性能应该不低吧😨😨，正式版倒是正常，就是dev版本帧率低
