### ISSUE TITLE
dev分支消失

### ISSUE THREAD

**Issue by Y-CIAO** [Steve-xmh/applemusic-like-lyrics#182]
dev分支为什么不见了，并且这个patchpatch-1分支是有什么新功能吗？我记得以前是有三个分支的：稳定，dev，patch1，但是patch1和稳定版差不多啊
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/132769718/d29df78f-eb2d-4609-a22d-825dff82e0f7)

**Comment by Steve-xmh** [comment]
正在准备下一个大版本的重构，仓库代码结构正在重新整理，所以现在开发分支的构建代码将不能被更新功能检测到
需要一点时间，等重构完成后这里会重新开放更新了
