### ISSUE TITLE
背景边缘闪烁

### ISSUE THREAD

**Issue by chali1997** [Steve-xmh/applemusic-like-lyrics#183]
背景有时候会出现闪烁，左上角可能比较明显，我不确定是BetterNCM的问题还是AMLL的问题，就先提一下吧

https://github.com/Steve-xmh/applemusic-like-lyrics/assets/58398544/2cb781f3-3f41-47e7-a7ed-4e61a36c34c8

**Comment by Steve-xmh** [comment]
严格来说这个是高斯模糊的天然特性，边缘因为模糊采样不足所以会有轻微闪烁
之后看看要不要缓解一下吧
