### ISSUE TITLE
歌词时长

### ISSUE THREAD

**Issue by Y-CIAO** [Steve-xmh/applemusic-like-lyrics#187]
当歌词时间较长时，渐变填充不会随时间长度而填充完，而是当歌词时长超过一定时间是，歌词再特定时间内就完成，及时歌词制作时还没有完成。举个例子，不如一句歌词的最后一个单词，时长设置的是3秒以内，那么制作时什么时候结束，播放时就什么时候结束，如果制作时设置的是5秒，则播放时3秒歌词就已显示完全。并且辉光也是这样，不会伴随整个时长。上述3，5秒仅为示意，不是实际时间。不知道重制版有无解决此问题

**Comment by Steve-xmh** [comment]
我的理解是，你想要在歌词编辑器内正确设置最后一行歌词的最后一个单词的结束时间，只要按下 H 键（即记录当前时间为当前单词的结束时间）即可
如果不是我说的这个情况的话，就再详细补充一下，是的话就可以关闭议题了。

**Comment by Y-CIAO** [comment]
我的意思是，当前插件播放时，如歌词结束时间在第五秒，由于时间过长，播放器在第三秒就播放完了

**Comment by Steve-xmh** [comment]
或者你说的是指 辉光动画 提早结束的情况（例如一个单词原本时长在 10 秒，但是辉光只用了 2 秒就完成效果了），这个是刻意而为的，因为网易云的逐词歌词很多时候最后一个单词都莫名其妙直接接着下一句的开头，所以就对太长的辉光效果做了限时。

**Comment by Y-CIAO** [comment]
我个人建议可以加长这个动画时长，并且辉光单词加入逐字母略微放大再缩小效果
