### ISSUE TITLE
歌词时长

### ISSUE THREAD

**Issue by Y-CIAO** [Steve-xmh/applemusic-like-lyrics#188]
当歌词时间较长时，渐变填充不会随时间长度而填充完，而是当歌词时长超过一定时间时，歌词在特定时间内就完成，即使歌词制作时还没有完成。举个例子，不比如一句歌词的最后一个单词，时长设置的是3秒以内，那么制作时什么时候结束，播放时就什么时候结束，如果制作时设置的是5秒，则播放时3秒歌词就已显示完全。并且辉光也是这样，不会伴随整个时长。上述3，5秒仅为示意，不是实际时间。不知道重制版有无解决此问题

**Comment by Steve-xmh** [comment]
#187 重复
