### ISSUE TITLE
添加歌词字体可变颜色

### ISSUE THREAD

**Issue by floatanddream** [Steve-xmh/applemusic-like-lyrics#190]
建议添加一个歌词字体取色模块，让字体贴合背景的颜色。
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/53161114/d31b544e-141a-4eff-8ae5-80fac8e77755)

**Comment by cale044** [comment]
要做的话整个开关
ps：我比较喜欢白色的
