### ISSUE TITLE
请求添加新功能：Apple Music 播放与暂停时专辑封面缩小与放大的效果

### ISSUE THREAD

**Issue by StevenCN1892** [Steve-xmh/applemusic-like-lyrics#191]
这个插件所谓：“最像 iPad 的 Apple Music 的歌词插件”，所以可不可以再完善一下呢。

https://github.com/Steve-xmh/applemusic-like-lyrics/assets/115457858/50ca20cf-e121-48ed-8361-f6c262ea835a
详情见视频

**Comment by Steve-xmh** [comment]
会加的，不过不必细究 README 上的一些说法
毕竟加了很多限定语

**Comment by StevenCN1892** [comment]
好吧

**Comment by Steve-xmh** [comment]
议题可以开着呀，这个效果确实没做

**Comment by StevenCN1892** [comment]
抱歉[doge]

**Comment by Steve-xmh** [comment]
开发版本已增加

**Comment by StevenCN1892** [comment]
感谢
