### ISSUE TITLE
背景渲染模块构建

### ISSUE THREAD

**Issue by floatanddream** [Steve-xmh/applemusic-like-lyrics#199]
位于core/bg–render模块是否可以单独构建做成一个组件还是说一定要绑定core目录下的其他组件才可以正常运行。
(用于美化学校期末大作业)😥😥😥

**Comment by Steve-xmh** [comment]
理论上是可以的，只是个人不想把模块拆的太散所以合在一块开发
如果你有特殊需要的话，可以单独拿出来使用，只需要安装pixi相关的依赖应该就可以工作了，具体可以检查一下package.json里的依赖信息

**Comment by floatanddream** [comment]
在本项目原有的基础上是可以成功运行的。
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/53161114/b2818d5a-3e99-4873-8470-ff83ada8928a)

但放在其他项目里安装，试了试import整个core组件，但是import不成功，在浏览器运行控制台提示AccessDenind不能访问模块。

然后试了试在Vue框架上构建，也是import问题。
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/53161114/deff8878-ea70-4439-8dd8-72a3d200c015)
无法找到模块“@applemusic-like-lyrics/vue”的声明文件。
尝试修改无果

**Comment by Steve-xmh** [comment]
> 在本项目原有的基础上是可以成功运行的。 ![image](https://user-images.githubusercontent.com/53161114/271782678-b2818d5a-3e99-4873-8470-ff83ada8928a.png)
> 
> 但放在其他项目里安装，试了试import整个core组件，但是import不成功，在浏览器运行控制台提示AccessDenind不能访问模块。
> 
> 然后试了试在Vue框架上构建，也是import问题。 ![image](https://user-images.githubusercontent.com/53161114/271782712-deff8878-ea70-4439-8dd8-72a3d200c015.png) 无法找到模块“@applemusic-like-lyrics/vue”的声明文件。 尝试修改无果

这个建议另外开启议题详细说明
