### ISSUE TITLE
[Bug/Enhancement] 歌词定位太慢

### ISSUE THREAD

**Issue by MicroCBer** [Steve-xmh/applemusic-like-lyrics#20]
![image](https://user-images.githubusercontent.com/66859419/212136412-055313fc-deaf-42dc-bf38-3415857018c3.png)

**Comment by Steve-xmh** [comment]
定位太慢是哪个方面的，动画还是歌词行的定位

**Comment by MicroCBer** [comment]
歌词行的定位

**Comment by Steve-xmh** [comment]
后面会整全局歌词定位时序调整的

**Comment by Steve-xmh** [comment]
已支持全局时间轴调节
