### ISSUE TITLE
项目导入问题

### ISSUE THREAD

**Issue by floatanddream** [Steve-xmh/applemusic-like-lyrics#200]
本项目原有基础上可以顺利运行。
![271782678-b2818d5a-3e99-4873-8470-ff83ada8928a.png](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/53161114/b14e421e-27be-4784-b3b2-8cc74054cb54)

尝试移植vue组件到其他vue项目时出现import错误![271782712-deff8878-ea70-4439-8dd8-72a3d200c015.png](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/53161114/2e657860-3d43-4bef-8224-8195eecbf3af)

提示未找到@amll/vue的文件声明。
amll-vue.mjs”隐式拥有 "any" 类型。
尝试修改声明还有尝试修改tsconfig文件compilerOptions无果。

**Comment by Steve-xmh** [comment]
如果方便，可以提供一下源代码仓库吗
如果实在不行，也可以整理出一个最小的可复现错误的版本仓库提供
因为所有的类型信息都是由 vite 构建产生的，package.json 也提供了类型文件路径，所以不太明白你的项目实际情况是如何的。但是考虑到隔壁 amll-ttml-tool 也是直接使用的 @amll/vue 模块且没有遇到类型解析问题，所以可能是你的项目配置在某个环节上出了问题。

**Comment by floatanddream** [comment]
我看了看本项目vue下的文件的package.json还有tsconfig.jsons确实是我配置出了问题，修改了一下已经能正确导入了。
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/53161114/6e483741-6b6e-4f66-896d-07a10d5a916d)


本项目的背景渲染模块能正确加载了。

**Comment by floatanddream** [comment]
> 如果方便，可以提供一下源代码仓库吗 如果实在不行，也可以整理出一个最小的可复现错误的版本仓库提供 因为所有的类型信息都是由 vite 构建产生的，package.json 也提供了类型文件路径，所以不太明白你的项目实际情况是如何的。但是考虑到隔壁 amll-ttml-tool 也是直接使用的 @amll/vue 模块且没有遇到类型解析问题，所以可能是你的项目配置在某个环节上出了问题。

如果不是提醒该看看package.json应该还要再弄一阵子哈哈哈

**Comment by floatanddream** [comment]
> > 如果方便，可以提供一下源代码仓库吗 如果实在不行，也可以整理出一个最小的可复现错误的版本仓库提供 因为所有的类型信息都是由 vite 构建产生的，package.json 也提供了类型文件路径，所以不太明白你的项目实际情况是如何的。但是考虑到隔壁 amll-ttml-tool 也是直接使用的 @amll/vue 模块且没有遇到类型解析问题，所以可能是你的项目配置在某个环节上出了问题。
> 
> 如果不是提醒该看看package.json应该还要再弄一阵子哈哈哈

谢谢大佬指引
