### ISSUE TITLE
专辑封面添加抗锯齿效果

### ISSUE THREAD

**Issue by HaoZi9167** [Steve-xmh/applemusic-like-lyrics#201]
在同一首歌曲中 amll封面与原封面相比锯齿明显
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/dd046738-5a94-4ee0-b231-1405bcd8908a)
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/138546084/a01426b2-e38b-49c5-aa04-1c5b3d538c07)

**Comment by HaoZi9167** [comment]
（似乎还有一部分降噪效果？）

**Comment by Steve-xmh** [comment]
网易云自己莫名其妙把图片的缩放方式改成了最近邻居（`image-rendering: pixelated;`）导致专辑图有噪点效果的缩放后会让噪点更明显，不知道他们怎么想的
之后会覆盖网易云的默认样式修正这个问题
然后这是原图对照（[http://p4.music.126.net/TE8Cw0oKemEGeIiI5yXGsA==/109951166424887673.jpg](http://p4.music.126.net/TE8Cw0oKemEGeIiI5yXGsA==/109951166424887673.jpg)）：

![https://p4.music.126.net/TE8Cw0oKemEGeIiI5yXGsA==/109951166424887673.jpg](https://p4.music.126.net/TE8Cw0oKemEGeIiI5yXGsA==/109951166424887673.jpg)
