### ISSUE TITLE
[Bug] 无法关闭“杂项”中的“下一次启动时显示教程”开关

### ISSUE THREAD

**Issue by ShigemoriHakura** [Steve-xmh/applemusic-like-lyrics#205]
网易云版本 3.0.0beta 201967
BetterNCM 1.3.0
AMLL版本 3.0dev 22c88d41

上面的显示帧数功能反而正常，下面的怎么按都没反应

**Comment by bhop0** [comment]
或许这个开关是3.0dev版本的开屏提示开关。作者在提示中说“不可关闭”，所以这个bug是有意为之。
