### ISSUE TITLE
2.1.8版本，背景渲染方式为流体效果时，GPU占用过高

### ISSUE THREAD

**Issue by ChrisYH20** [Steve-xmh/applemusic-like-lyrics#209]
如题，此时调用的显卡为R7-5800H的核显是Radeon Vega8，512m显存，使用率几乎都在百分之90以上
![屏幕截图 2023-11-04 153420](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/140259582/381a8ec0-4105-4d88-9b48-c476ad8ebf97)

**Comment by Steve-xmh** [comment]
背景占用就是这么高的，请使用独立显卡以分担压力
你可以参考 https://github.com/Steve-xmh/applemusic-like-lyrics/discussions/206 中大家的数据来估测自己的播放流畅水平
