### ISSUE TITLE
歌词界面闪烁

### ISSUE THREAD

**Issue by closerRen** [Steve-xmh/applemusic-like-lyrics#210]
播放时界面闪烁，外置播放器也存在这个问题。

https://github.com/Steve-xmh/applemusic-like-lyrics/assets/100517599/c5a62d29-cc0a-47af-84e2-6d1cf45ecd03

网易云版本：3.0.0
batterncm版本：1.3.0
amll版本：3.0-beta-3.0.0-3253bd96

**Comment by Steve-xmh** [comment]
https://github.com/Steve-xmh/applemusic-like-lyrics/discussions/206
目前已知会影响插件演出效果的BNCM插件如下，除非插件有所改善，否则尽量不要配合以下插件使用：

- UnblockNeteaseMusic : 会导致播放进度间歇性归零，影响动画效果
- LibFrontendPlay : 疑似导致播放掉帧（见 https://github.com/Steve-xmh/applemusic-like-lyrics/discussions/206#discussioncomment-7551251 ）

**Comment by HaoZi9167** [comment]
感觉像是返回歌曲播放时长时不断跳转到0:00的问题...

**Comment by Steve-xmh** [comment]
> 感觉像是返回歌曲播放时长时不断跳转到0:00的问题...

是那个解灰插件的问题，会循环请求某个VIP接口，然后解灰服务器返回了错误的结果，导致网易云重置播放进度，如此往复导致的

**Comment by closerRen** [comment]
我安装了UnblockNeteaseMusic插件，估计这就是原因。

**Comment by closerRen** [comment]
确实如此，卸载了解灰插件后问题解决了。
