### ISSUE TITLE
交叉对唱时未唱完的歌词行被推到模糊区

### ISSUE THREAD

**Issue by blueset** [Steve-xmh/applemusic-like-lyrics#217]
当两个歌手交叉对唱时，后起唱的歌词会把先前未唱完的歌词推倒上方模糊区，但歌词进度动画效果仍继续。

建议避免将正在进行中的歌词套上模糊效果或推出歌词对齐线外。

测试用版本： `@applemusic-like-lyrics/react@0.0.15`

<img width="954" alt="image" src="https://github.com/Steve-xmh/applemusic-like-lyrics/assets/553831/6753ed31-3918-4aff-b5a4-e20701f713ef">

范例： https://codesandbox.io/p/devbox/rjmcv4

**Comment by Steve-xmh** [comment]
这个应该是不会出现的，有可能是歌词文件的时间轴有误，或者赋予给组件的播放进度精度和频率不够，你的歌词文件可以分享一下吗？
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/39523898/e34fcbff-0ecf-4d85-805f-1c1e26a71f36)

**Comment by Steve-xmh** [comment]
看了一下你的歌词数据，其中歌词行的 `endTime` 并没有大于等于最后一个单词的结束时间，导致演出出错，你可能需要修正一下歌词数据才能正确呈现效果。

**Comment by blueset** [comment]
确实是我的歌词数据生成逻辑的问题，感谢指正！
