### ISSUE TITLE
希望可以分别设置已播放和未播放歌词的颜色

### ISSUE THREAD

**Issue by gongfuture** [Steve-xmh/applemusic-like-lyrics#26]
如题，主要是觉得未播放的歌词亮度太高看的不舒服qwq

**Comment by Steve-xmh** [comment]
因为众口难调，而且加太多可配置项目也会让设置变得混乱。
如果对默认样式不太满意的话，可以通过自定义 CSS 功能自行对样式做覆盖。
如有不便还请谅解。

**Comment by gongfuture** [comment]
了解，感谢作者回复
