### ISSUE TITLE
对歌词较多的歌曲做性能优化

### ISSUE THREAD

**Issue by jiajiaxd** [Steve-xmh/applemusic-like-lyrics#30]
如图，在此类长达几十分钟的歌曲中，由于歌词较多，歌词浮动掉帧较为明显。
![image](https://user-images.githubusercontent.com/51043917/212921535-734700c7-258a-4182-94fe-0dff925c02cd.png)
仅提出此问题，不知道有没有办法解决......

**Comment by Steve-xmh** [comment]
掉帧很难解决呢，再加上逐词歌词会将每个词切片且克隆出一个用于动画的版本，歌词过多的情况下滚动卡顿无法避免呢。。。

之后会想办法看看如何优化的，这首歌可以的话可以分享一份链接给我，我有空去听一下。

**Comment by Steve-xmh** [comment]
尝试优化了一下性能，可以在 Github Release 里下载最晚构建来尝试一下，看一下是否有所改善

**Comment by jiajiaxd** [comment]
![image](https://user-images.githubusercontent.com/51043917/213905469-9ff29b2c-2360-48f8-b509-2f338d4d9e79.png)
更新最新版本后，歌词页无法加载。
旧版本没有该问题。

**Comment by Steve-xmh** [comment]
已经做了力所能及的临时优化，现在这首歌已经可以做到全特效 60FPS 了（至少在我的电脑上是了）
会在下一个正式版本中引入
