### ISSUE TITLE
歌曲搜索栏字体变成宋体

### ISSUE THREAD

**Issue by linghies** [Steve-xmh/applemusic-like-lyrics#31]
版本：1.6.2
网易云版本：2.10.6
貌似安装插件后，搜索栏中的字体会从微软雅黑变成宋体。
默认情况下（安装插件之前）：
![Snipaste_2023-01-19_11-29-35](https://user-images.githubusercontent.com/59905055/213349166-8ff45f15-6c78-43cb-afae-b3bb78787d3b.png)

（安装插件后）字体就发生了变化，貌似其他地方都正常，噢对了，还有歌词界面的“音”/“译”字样也是，这是什么原因呢？
![Snipaste_2023-01-19_11-36-29](https://user-images.githubusercontent.com/59905055/213349624-29323077-173c-45cb-ab1d-c14b30d4e405.png)

**Comment by Steve-xmh** [comment]
尝试修正了一下，请前往 Github Release 下载最新开发版本，看一下能否正确修复

**Comment by linghies** [comment]
已更新开发版本。情况似乎变得更糟糕了，歌词界面貌似丢失，重启后问题仍复现。退回1.6.2时恢复正常 :
![121](https://user-images.githubusercontent.com/59905055/213699958-30e75857-1a9a-499a-bd89-17def89a8513.png)
![120](https://user-images.githubusercontent.com/59905055/213699645-e27729eb-18d8-41c1-ae38-6d760d926173.png)

**Comment by linghies** [comment]
刚刚再试了一次 ╮（╯＿╰）╭，尝试把所有无关插件清除掉，只留下1.6.3插件，貌似也还是这个样子，没有改善......（所以应该不是插件冲突导致的）
有点怀疑是不是我的Win10系统本身出问题了.....((/- -)/

**Comment by Steve-xmh** [comment]
> 刚刚再试了一次 ╮（╯＿╰）╭，尝试把所有无关插件清除掉，只留下1.6.3插件，貌似也还是这个样子，没有改善......（所以应该不是插件冲突导致的）
> 有点怀疑是不是我的Win10系统本身出问题了.....((/- -)/

没事，先留着吧，等年后回来用上 Windows 的电脑再详细测试一下

现阶段先回到正式版本然后用诸如 TinyNCM 等能编辑字体样式的插件来修改字体吧

**Comment by Steve-xmh** [comment]
已自查修复，会在未来正式版中加入
