### ISSUE TITLE
歌词播放错误，部分歌词无翻译

### ISSUE THREAD

**Issue by feng-or** [Steve-xmh/applemusic-like-lyrics#32]
![image](https://user-images.githubusercontent.com/104701550/213454490-3d4c2031-341c-4976-8d05-4d3812d220d3.png)
此处还是前奏但是已经开始走歌词
![image](https://user-images.githubusercontent.com/104701550/213454064-ebbe0136-6953-46b1-b07d-e53d1d9c02ea.png)
此处歌词无翻译

**Comment by Steve-xmh** [comment]
这个是正常的，如果启用逐词歌词，则使用逐词歌词版本的歌词进行解析播放。

这个的行为是和手机版本的网易云一致的，请和手机版的网易云对照一下即可。

任务栏歌词插件默认使用无逐词歌词校对的版本，所以翻译是完整的。
