### ISSUE TITLE
[Enhancement] 背景色和评论区文字颜色类似导致看不清评论

### ISSUE THREAD

**Issue by ningguolin** [Steve-xmh/applemusic-like-lyrics#37]
把歌曲封面放大加模糊效果作为背景很好看，但是滚动到评论区有些背景色和文字颜色类似就会导致看不清评论。
希望在下一版本中能适当优化一下评论区的背景处理方式，或者使用其他替代方案以便于修复这类问题。
如下图所示：
![image](https://user-images.githubusercontent.com/37262548/215025571-0e14935a-b608-486b-85b0-cc0d0b926363.png)

**Comment by Steve-xmh** [comment]
已支持调节背景亮度，会在之后的版本支持
