### ISSUE TITLE
无法点击歌词跳转播放

### ISSUE THREAD

**Issue by windy1021** [Steve-xmh/applemusic-like-lyrics#39]
之前使用Apple Music-like lyrics的时候可以点击某行歌词跳转播放，但今天点击无效，以为是插件冲突，卸载后安装发现可以点击跳转，但装了别的插件之后，该功能就失效了，不论先后顺序都会失效

BetterNCM 版本
1.0.0

网易云音乐版本
2.10.6

网易云音乐 Patch 版本
5ad43a6

已安装插件
Apple Music-like lyrics
Material You
TinyNCM
ActionEnhancement
FluentProgressBar
RoundComerNCM
这首歌的封面是什么？

**Comment by Steve-xmh** [comment]
会在 #34 中统一修复，在那之前如果遇到这个情况请尝试在歌词页面时暂停音乐再播放，应该可以临时解决问题。

**Comment by windy1021** [comment]
> 会在 #34 中统一修复，在那之前如果遇到这个情况请尝试在歌词页面时暂停音乐再播放，应该可以临时解决问题。

好的谢谢大佬，辛苦啦

**Comment by Steve-xmh** [comment]
已修复，会在未来正式版中加入
