### ISSUE TITLE
配置界面不显示

### ISSUE THREAD

**Issue by HandwerSTD** [Steve-xmh/applemusic-like-lyrics#4]
网易云版本 2.10.6，BetterNCM版本 0.2.5

打开的一瞬间会显示配置界面，整个页面加载出来之后就不显示了

安装的插件 BGEnhanced TinyNCM

<img width="489" alt="Snipaste_2023-01-03_11-05-45" src="https://user-images.githubusercontent.com/37949764/210295433-b3249460-a862-4358-9408-c42ddbfd0e24.png">

**Comment by Steve-xmh** [comment]
请使用 BetterNCM 1.0.0 预览版本及更新版本加载本插件

旧版 BetterNCM 不再兼容
