### ISSUE TITLE
歌词界面与评论区间有较长间隔

### ISSUE THREAD

**Issue by Titanium-alloyMC** [Steve-xmh/applemusic-like-lyrics#40]
从歌词下滑到评论时，中间有一段空白。窗口状态已为最大化
![屏幕截图 2023-01-30 113631](https://user-images.githubusercontent.com/78596871/215382426-4aaab5a4-b352-4541-a0f8-cc93a2620776.png)

**Comment by Steve-xmh** [comment]
这个是刻意的，不然不太美观
