### ISSUE TITLE
根据专辑主题色改变渲染逻辑

### ISSUE THREAD

**Issue by Titanium-alloyMC** [Steve-xmh/applemusic-like-lyrics#42]
在遇到专辑图大片为白色时自动改变主题色或调整背景亮度，不然直接看不到字了。（虽然调亮度就能看见了，但很多人第一次看到会蒙
插件版本：1.7.1(Lastest)
示例曲：One Last Kiss/ 糸
前图为默认亮度，后图为亮度-30%
![屏幕截图 2023-01-31 192502](https://user-images.githubusercontent.com/78596871/215749239-b324b1ae-6cd3-4819-a667-e49277be4b07.png)
![屏幕截图 2023-01-31 193913](https://user-images.githubusercontent.com/78596871/215750275-f74b1de8-4c5b-4308-8289-c20cc1cc3a24.png)

**Comment by Steve-xmh** [comment]
目前已对主题色采样进行了调节，应该会有所改善，日后也会提供动态根据背景样式改变文字颜色的选项
更新将在下一个次要版本号推出
