### ISSUE TITLE
无法更新1.7.1

### ISSUE THREAD

**Issue by windy1021** [Steve-xmh/applemusic-like-lyrics#44]
[![image](https://user-images.githubusercontent.com/62731276/215760634-097d54d8-a066-40e4-8c22-93bf9a91e091.png)](https://files.catbox.moe/ns0014.png)
点更新一直加载中，在Git下载移入插件文件夹却显示是1.70版本仍需更新

**Comment by Steve-xmh** [comment]
这个是插件商店的问题，Github Release 这边我没来得及增加版本，过一会加上
