### ISSUE TITLE
歌词高亮位置显示问题

### ISSUE THREAD

**Issue by SakuraTao2007** [Steve-xmh/applemusic-like-lyrics#45]
对于当前歌词，在 “音乐详情页” 在顶端时显示正常的，但是向下拉一小段距离后
高亮位置也会跟着下移，

正常显示截图：
![image](https://user-images.githubusercontent.com/59493751/215994766-b5e9f9d6-4793-45c7-a843-0cc3ae32d118.png)

问题所在截图：
![image](https://user-images.githubusercontent.com/59493751/215994708-7dac419a-cfeb-4ea6-8fee-814de5f50057.png)

导致因素：
我个人猜是高亮位置选择的是当前窗口渲染的中间位置导致的

这本不是什么大的问题，主要的影响是：
从评论区返回顶端后需要等播放到下一句歌词时才能重回正常位置显示

**Comment by Steve-xmh** [comment]
已修复
