### ISSUE TITLE
为什么在这下的 1.7.1 还要在wyy更新 但是 更新不了  下载也不行

### ISSUE THREAD

**Issue by swy4four** [Steve-xmh/applemusic-like-lyrics#46]

**Comment by Steve-xmh** [comment]
请提供详细信息，否则我无法理解问题

**Comment by swy4four** [comment]
我无法在网易云下载您的插件&nbsp; 但是在Github中下载的可以使用但是需要在网易云中更新 但是我无法更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月2日(周四) 中午12:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Steve-xmh/applemusic-like-lyrics] 为什么在这下的 1.7.1 还要在wyy更新 但是 更新不了  下载也不行 (Issue #46)




 
请提供详细信息，否则我无法理解问题

**Comment by Steve-xmh** [comment]
插件无法下载是 插件商店 这个插件的问题，和我的插件无关。

Github 上的版本我忘记调节版本号了，可以忽略，实际上是 1.7.1 的。

**Comment by swy4four** [comment]
谢谢大佬 解答&nbsp;

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月2日(周四) 中午12:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Steve-xmh/applemusic-like-lyrics] 为什么在这下的 1.7.1 还要在wyy更新 但是 更新不了  下载也不行 (Issue #46)




 
插件无法下载是 插件商店 这个插件的问题，和我的插件无关。
 
Github 上的版本我忘记调节版本号了，可以忽略，实际上是 1.7.1 的。
