### ISSUE TITLE
BugReport failed to find family name 苹方 常规: err 0 not_found: -1

### ISSUE THREAD

**Issue by kinney-08** [Steve-xmh/applemusic-like-lyrics#47]
failed to find family name 苹方 常规: err 0 not_found: -1

这行字在终端无限循环，尽管我已经安装了苹方字体并且界面也使用了苹方字体
有点妨碍到看终端了

**Comment by Steve-xmh** [comment]
你应该是启用了 Canvas 渲染，目前为了调试和功能测试使用的字体是苹方字体（也就是 Canvas 中上下文的 `font` 属性会在每次绘制时设置成 `PingFang SC`）。[具体可以查阅此处的代码。](https://github.com/Steve-xmh/applemusic-like-lyrics/blob/b915ef4d7026b2f0cd8b033417f8f9319f598a7f/src/components/lyric-canvas-renderer/render.ts#L42)

如果是以上情况的话，我猜测是因为你没有完整安装苹方字体导致的（苹方 常规 字体对应的字体文件是 [PingFang Regular.ttf](https://github.com/paraself/PingFang-Fonts/blob/master/PingFang%20Regular.ttf)），如果情况不是我所说的那样的话，请展开该错误日志行并截图，我好确认一下是什么情况。

（注：目前 Canvas 渲染后端还在开发，如果问题都是出自于该后端的话则不会处理该 Issue）

**Comment by Steve-xmh** [comment]
长时间未回复，已关闭
