### ISSUE TITLE
歌曲播放截面一直显示“快来说点什么吧” 请问应该怎么消除

### ISSUE THREAD

**Issue by LonelyTom** [Steve-xmh/applemusic-like-lyrics#48]
歌曲播放截面一直显示“快来说点什么吧” 请问应该怎么消除
![image](https://user-images.githubusercontent.com/48714655/216919390-d43c0c96-7142-40f0-bb81-47bf246e756e.png)

**Comment by LonelyTom** [comment]
已经解决了

**Comment by Qiaofanxing** [comment]
怎么解决的，我也遇见了，求解决方法
