### ISSUE TITLE
[ 功能请求 ] 自定义CSS中

### ISSUE THREAD

**Issue by Satan123231** [Steve-xmh/applemusic-like-lyrics#49]
![image](https://user-images.githubusercontent.com/41412981/217234243-fee30c8e-393f-4570-9167-10205d550979.png)
###如果可以像 `StyleSnippet` 这样 **自定义** 更改就好了 :D

**Comment by Steve-xmh** [comment]
直接用 StyleSnippet 吧，AMLL 的自定义 CSS 功能其实和这个一样的
之后计划移除掉自定义 CSS 功能了
