### ISSUE TITLE
歌词加载失败

### ISSUE THREAD

**Issue by KeeLee2005** [Steve-xmh/applemusic-like-lyrics#5]
![QQ截图20230105093639](https://user-images.githubusercontent.com/92454987/210681892-e778c5ef-24c2-41ac-baa0-fd56d18ca3d0.png)
如图所示报错
BetterNCM 1.0.0，网易云版本2.10.4（Build200396）
已安装插件：
ActionEnhancement-0.1.4
Apple-Musiclike-Lyrics-1.2.0
MikuPlugin
MoTheme-1.1.10
RoundCornerNCM-0.1.1
What-is-the-cover-of-this-music-1.0.2

**Comment by Steve-xmh** [comment]
请尝试使用插件设置里的搜索函数功能找到对应的加密请求函数，如果可以找到且正常工作的话就关闭这个 Issue 吧。

如果无法找到的话，就提供一下 core.js 的版本（搜索函数那块会有写）和源文件，我帮你看看。

**Comment by KeeLee2005** [comment]
应该是网易云版本过低所致，更新后已修复
