### ISSUE TITLE
播放界面歌曲别名不能居中

### ISSUE THREAD

**Issue by Nuit5566** [Steve-xmh/applemusic-like-lyrics#50]
歌名歌手专辑居中居左好像也无法调整
![image](https://user-images.githubusercontent.com/63411237/217495901-e902e0bc-0a39-4ffe-b0dd-b993ac9753a9.png)
![image](https://user-images.githubusercontent.com/63411237/217495972-bdb27cbf-dd9a-4cb9-9c6c-ef5f5053162f.png)

**Comment by Steve-xmh** [comment]
v1.8.2 已修正
