### ISSUE TITLE
[v1.8.2]背景亮度无法调节

### ISSUE THREAD

**Issue by muga-cat** [Steve-xmh/applemusic-like-lyrics#51]
背景设置里调整背景专辑图采样色亮度对播放界面里背景图的亮度没有影响
还有为什么把之前歌词顶部的按钮都收到下列菜单里。。。切换全屏模式麻烦了好多（残念
![image](https://user-images.githubusercontent.com/122970101/217527891-e96bda8a-7bfd-4e2b-84fe-36bb5e856703.png)

**Comment by Steve-xmh** [comment]
为了页面整洁，且能确保歌词的滚动测量稳定，把原先的按钮都移动到了菜单内
（其实按大家的使用频率而言其实麻烦不到哪里去的）
采样色，顾名思义，是一个从专辑图里提取出来的主题颜色色表，所以修改的不是专辑图的亮度，而是这个色表的亮度，而使用了色表的只有流体效果。
专辑图片的配置功能有时间会出的，还请耐心等待（已经连续更新了好几天了，体谅一下吧）

**Comment by muga-cat** [comment]
谢谢大佬啦 关于背景亮度我记得v1.7.1是可以调节的所以我以为出了bug

**Comment by Steve-xmh** [comment]
> 谢谢大佬啦 关于背景亮度我记得v1.7.1是可以调节的所以我以为出了bug

其实现在的背景也是可以配置明暗的，只是我还没有想好要如何去写配置页面和保存和调用配置的办法，所以没办法直接调。
所以我先给专辑图片效果的背景加了一个限制明度的处理，以免过亮导致文字看不见。
（不过没有给亮色主题做处理，所以如果是亮色的话就看不清了）
