### ISSUE TITLE
1.8 更新以后的3个问题

### ISSUE THREAD

**Issue by planetarian10** [Steve-xmh/applemusic-like-lyrics#52]
个人看法，希望开发者大大看下。
1.与BGEnhanced插件冲突问题。
具体问题写在图里了。
![QQ截图20230208210826](https://user-images.githubusercontent.com/60946481/217542468-bf2a5854-7aaf-4da4-9ce6-e0d8e54a0563.png)
![QQ截图20230208210944](https://user-images.githubusercontent.com/60946481/217542540-03045f0e-50f4-4352-b7ad-08405b092044.png)
![QQ截图20230208211305](https://user-images.githubusercontent.com/60946481/217542564-54cbf2fa-61fd-47fe-b05c-776ca05644ea.png)
![QQ截图20230208211359](https://user-images.githubusercontent.com/60946481/217542598-fb5ec9d8-2c0c-4b19-8440-1c8f58d600ac.png)
2.播放界面的布局个人感觉不如1.7，是本来就是这样设计的吗？
同样的，问题写在图里了，前为1.7版本，后为1.8版本。
![QQ截图20230208211657](https://user-images.githubusercontent.com/60946481/217543218-f7f66a5f-f9ed-48da-bda3-c089e234cb8b.png)
![QQ截图20230208211512](https://user-images.githubusercontent.com/60946481/217543246-407b3db6-a920-44dd-8780-60fd8d45541f.png)
3.一个小bug，插件自带的更新提示没有正确检查到更新。
![QQ截图20230208212202](https://user-images.githubusercontent.com/60946481/217543369-840196bb-a8b8-477a-bcce-3973c9d4a680.png)

**Comment by Steve-xmh** [comment]
第一个问题的话，关闭背景就不会绘制 AMLL 自带的背景，之后便可以使用其他插件提供的背景。（再往后就不是 AMLL 的处理范围了）
（如果问题还存在的话，可能需要其他插件向 AMLL 进行兼容了（毕竟关闭了背景确实完全不会渲染了）。
第二个问题的话，是按照 Apple Music 的 macOS 版本的全屏状态重新设计的布局，专辑图片是居中的，而歌曲信息会贴靠图片的下方。可以通过打开隐藏播放栏功能来解决这个观感问题。（如果还是介意这个布局的话，之后我再考虑把之前的布局加回来）
第三个问题，更新到 1.8.2 即可。

综上，请有针对性地发 Issues，而不是几个问题贴在一起，否则很不好追踪问题。因此先关闭这个 Issue 了。
