### ISSUE TITLE
1.8版本 播放界面模糊渲染问题

### ISSUE THREAD

**Issue by planetarian10** [Steve-xmh/applemusic-like-lyrics#53]
对 #52 中的第一个问题表述进行修正。
经过进一步使用，与BGEnhanced插件无关，问题出在模糊的渲染上。
图1为1.7版本，模糊正常。
图2为1.8版本0.5比率，图3为0.1比率，模糊后的背景似乎有网格状的纹理（尤其是专辑封面的文字附近最为明显），反复调整背景渲染分辨率比率，问题依然存在。
不知道是不是个例，我的显卡是intel核显。
![QQ截图20230208231110](https://user-images.githubusercontent.com/60946481/217572195-f95f682c-9182-4a53-92fc-e62300ef84fd.png)
![QQ截图20230208231229](https://user-images.githubusercontent.com/60946481/217572220-6f2cb1ae-e3b4-4a38-bcea-9ec6ff8a7070.png)
![QQ截图20230208231255](https://user-images.githubusercontent.com/60946481/217572233-c3b71afe-102c-45f4-b6ac-a57525346638.png)

**Comment by Steve-xmh** [comment]
已修正，在下一个修订版本会提供
