### ISSUE TITLE
新版本使用专辑图片背景时，背景设置里亮度调节失效

### ISSUE THREAD

**Issue by moWhite43** [Steve-xmh/applemusic-like-lyrics#54]
![image](https://user-images.githubusercontent.com/53568479/217781255-608de710-ef27-4981-8cd2-2edf7a879672.png)
![image](https://user-images.githubusercontent.com/53568479/217781397-e7a1de51-5e2e-44d5-8569-bf04f8fea248.png)
如图，调节亮度调节进度条时背景无变化，1.7.1版本可以正常使用

**Comment by Steve-xmh** [comment]
https://github.com/Steve-xmh/applemusic-like-lyrics/issues/52#issuecomment-1422711449
