### ISSUE TITLE
1.8.2中歌曲信息有时被部分遮挡/苹方字体失效

### ISSUE THREAD

**Issue by yijiaqu** [Steve-xmh/applemusic-like-lyrics#56]
在1.8.2版本中，专辑封面位置进行了调整。在全屏模式且隐藏播放栏下，此专辑封面位置确实更接近macOS使用场景；但播放栏显示时，部分歌曲信息可能会被播放栏遮挡。如图1，歌曲信息全为英文时不会被遮挡；而在图二情况下，由于歌曲信息中有汉字导致信息下沉较大。
![1](https://user-images.githubusercontent.com/57066567/218107608-658e0823-20b4-43c7-a21d-ff86d9cf851c.png)
![2](https://user-images.githubusercontent.com/57066567/218107653-2d9a0ee9-db84-49f8-a3c9-8e656f9a6144.png)
非全屏模式下，个人更喜欢上一版样式，可能的话希望能够提供选项。
另，如图，此版本更新后，苹方字体疑似无法应用在播放页面。我确信正确安装了PingFang SC字体，且在之前版本中并没有出现此问题。
感谢作者开发优质插件。

**Comment by Steve-xmh** [comment]
已修复，下一个修订版本会应用
