### ISSUE TITLE
FM 歌词显示位置偏下

### ISSUE THREAD

**Issue by SakuraTao2007** [Steve-xmh/applemusic-like-lyrics#57]
![image](https://user-images.githubusercontent.com/59493751/218297809-50bb8852-205a-49bc-93bb-8d7507c5e5b5.png)

如果不是刻意为之，那么就是 bug 了

**Comment by wddxg** [comment]
![image](https://user-images.githubusercontent.com/48612121/220924095-b5e7b4d7-0b8b-43de-8bbe-5223339f8a86.png)
fm里面歌名字体好大 显示不全 是我设置的问题吗QAQ

**Comment by Steve-xmh** [comment]
> ![image](https://user-images.githubusercontent.com/48612121/220924095-b5e7b4d7-0b8b-43de-8bbe-5223339f8a86.png) fm里面歌名字体好大 显示不全 是我设置的问题吗QAQ

不采纳开发版本的任何问题

**Comment by Steve-xmh** [comment]
已修正，将在下一个正式版本推出
![image](https://user-images.githubusercontent.com/39523898/221408170-fdefab7d-f89e-4428-902c-435a566cce4f.png)
