### ISSUE TITLE
重启网易云后AMLL的配置会恢复为默认

### ISSUE THREAD

**Issue by floatanddream** [Steve-xmh/applemusic-like-lyrics#58]
重启网易云后AMLL的配置会恢复为默认
AMLL版本：v1.8.5

**Comment by Steve-xmh** [comment]
![image](https://user-images.githubusercontent.com/39523898/218517668-3bfbfb97-625f-4583-97b4-38b6bfcf0e8a.png)

**Comment by floatanddream** [comment]
每次重启网易云都会恢复默认这是正常的嘛

**Comment by floatanddream** [comment]
> ![image](https://user-images.githubusercontent.com/39523898/218517668-3bfbfb97-625f-4583-97b4-38b6bfcf0e8a.png)
> 

每次重启网易云都会恢复默认这是正常的嘛

**Comment by Steve-xmh** [comment]
请检查一下插件文件夹下的插件配置文件 `amll-settings.json` 的内容 `C:\betterncm\plugins_dev\Apple-Musiclike-lyrics\amll-settings.json`

如果内容存在且格式正确则检查一下 DevTool 输出是否有类似 `警告：AMLL 插件配置读取失败` 的日志。

**Comment by floatanddream** [comment]
> 有类似的
![image](https://user-images.githubusercontent.com/53161114/218521600-6839f03c-b998-4f7a-9694-8d6cb4a45bf8.png)

**Comment by Steve-xmh** [comment]
v1.8.6 应该修好了
