### ISSUE TITLE
歌曲信息修改颜色？

### ISSUE THREAD

**Issue by DOGqPolice** [Steve-xmh/applemusic-like-lyrics#59]
不知道是我的问题还是插件问题，歌曲信息都是黑色的？遇到深色的专辑封面就完全看不清了。。。。

**Comment by Steve-xmh** [comment]
如果是歌曲信息的文字是黑色的但是歌词是正常的颜色的话，那就是其他插件干扰了 AMLL 的歌词信息字体颜色，自行检查是什么插件的问题吧。

如果是上述情况，请自行关闭 Issue，如果不是的话，提供一下实际截图我看一下情况。

**Comment by Steve-xmh** [comment]
已在开发版本修正
