### ISSUE TITLE
[Bug]翻译开关导致歌词错位归正不及时

### ISSUE THREAD

**Issue by KJH-x** [Steve-xmh/applemusic-like-lyrics#6]
感谢优秀的插件

在播放的时候点击翻译的开关切换有无翻译的时候，要到下一句歌词才能恢复与进度条同步，即点击的时候，焦点歌词行会离开显示区域，到下一句歌词时才更新位置。

建议再切换时立刻执行一次归位

**Comment by Steve-xmh** [comment]
已修正
