### ISSUE TITLE
歌词

### ISSUE THREAD

**Issue by lhcc14** [Steve-xmh/applemusic-like-lyrics#60]
网易云界面处于歌词界面最小化会停止渲染，但关闭后仍在渲染
<img width="1280" alt="屏幕截图 2023-02-21 112201" src="https://user-images.githubusercontent.com/108203204/220239605-dbf0e780-a812-47c8-9549-e5b680018124.png">
<img width="1280" alt="屏幕截图 2023-02-21 112242" src="https://user-images.githubusercontent.com/108203204/220239615-bce4a630-32e7-457b-bdba-c0132f145b88.png">
<img width="1280" alt="屏幕截图 2023-02-21 112123" src="https://user-images.githubusercontent.com/108203204/220239617-f980d7e6-0848-4309-852f-19a5101e6acf.png">
<img width="1280" alt="屏幕截图 2023-02-21 112150" src="https://user-images.githubusercontent.com/108203204/220239620-abe0ce2b-0a1c-4188-8eda-64c05a7d0e86.png">

**Comment by Steve-xmh** [comment]
这个是网易云自己的问题
