### ISSUE TITLE
歌词滚动动画拖沓

### ISSUE THREAD

**Issue by TreeYeah** [Steve-xmh/applemusic-like-lyrics#61]
建议改回原来的同步滚动，要不就给个选项。谢谢作者！

**Comment by Steve-xmh** [comment]
歌词为了方便观看会对播放过快的歌词行做停顿缓冲，这个也是 Apple Music 歌词的基本操作。
如果是这个停顿缓冲觉得不太喜欢的话，新版本会提供配置选项以禁用。
如果不是的话，可以详细描述一下拖沓的实际情况吗？

**Comment by TreeYeah** [comment]
抱歉没说清楚。就是当前行的歌词就位后，未播放歌词在一个回缩的动画而后才归位，个人感觉有点不和谐。

**Comment by Steve-xmh** [comment]
理解了，这个是原先歌词渲染方式的已知缺陷，新版本已经重构了歌词渲染方式，可以正确归位歌词了。
详情可以查看我刚刚发的[ 2.0 演示视频](https://www.bilibili.com/video/BV1nT411i75v/)

**Comment by Steve-xmh** [comment]
新版本将会推出，这个就先关闭了

**Comment by windy1021** [comment]
> 新版本将会推出，这个就先关闭了

大佬新版本啥时候更新呀，看了视频太期待了
