### ISSUE TITLE
无法显示歌词 /  歌词超出规定范围

### ISSUE THREAD

**Issue by WorldSansha** [Steve-xmh/applemusic-like-lyrics#62]
如题

https://user-images.githubusercontent.com/37899975/221343753-a77c8e67-07ef-4d4c-afda-57bedc2c16a0.mp4

**Comment by Steve-xmh** [comment]
> 如题
> 
> https://user-images.githubusercontent.com/37899975/221343753-a77c8e67-07ef-4d4c-afda-57bedc2c16a0.mp4
> 
> 

不采纳开发版本的任何问题
