### ISSUE TITLE
[BUG]逐词歌词显示错误

### ISSUE THREAD

**Issue by KJH-x** [Steve-xmh/applemusic-like-lyrics#66]
字母下探部分有一部分没有覆盖上亮色
<img width="649" alt="截图_20230308122812" src="https://user-images.githubusercontent.com/53437291/223619791-9057e7cd-b03f-4869-bdbf-b7d86deab324.png">
歌词设置：
<img width="474" alt="截图_20230308123128" src="https://user-images.githubusercontent.com/53437291/223620116-d60cf8b5-7160-41fb-baa5-2c2f95652166.png">

所用字体：思源宋体 CN Heavy

**Comment by KJH-x** [comment]
另外建议添加个配置导出导入的操作？这样之后的分享、Issue都方便一点（个人观点）

**Comment by Steve-xmh** [comment]
这个逐词高亮显示不全的问题在开发版本已重构修复
配置文件是存储在 `betterncm文件夹/amll-data/amll-settings.json` 里的，可以自行复制或者替换
