### ISSUE TITLE
播放页面和主页满满的割裂感

### ISSUE THREAD

**Issue by LinJie-mjyb** [Steve-xmh/applemusic-like-lyrics#67]
感觉整个UI界面很完美，远远大于预期，但是越是完美的播放界面就越与主页形成反差
我试了好几个主题，都没有达到满意的状态
所以我感觉直接从整个主题入手，将整体UI统一化，这样就显得很舒服

**Comment by Steve-xmh** [comment]
虽然我也有想过要不要制作主题
但是很可惜精力有限，为了磨出这样的效果已经花了太多精力了，实在腾不出时间做其他东西
Issue 先这样挂着吧，蹲一位大佬来做一个类 Apple Music 的主题样式或者我什么时候有时间去做这个东西吧。

**Comment by LinJie-mjyb** [comment]
大佬辛苦了，确实做的很精致，没有太多精力能理解，而且这东西开源不收费，还是恰饭要紧，优化慢慢来，感受到大佬的热爱了~

**Comment by SkeletoNCY** [comment]
同样希望大佬继续加油！感谢大佬制作的插件

**Comment by Steve-xmh** [comment]
考虑到网易云 3.0.0 的 UI 大量重写，我想至少不丑了，就关掉这个 Issue 了
