### ISSUE TITLE
歌词间隔错误与显示不全

### ISSUE THREAD

**Issue by 22Frederic** [Steve-xmh/applemusic-like-lyrics#68]
歌词间隔在位置情况下间隔错误
![屏幕截图 2023-03-12 120931](https://user-images.githubusercontent.com/105597335/224524543-d76ae264-8c04-4934-b164-d5e0a26d78c7.png)
或者后面的歌词无法加载
![屏幕截图 2023-03-12 121814](https://user-images.githubusercontent.com/105597335/224524559-5b687771-6566-4260-8252-039774bd2123.png)
另外英文歌词显示不全（使用苹方）
![屏幕截图 2023-03-12 121016](https://user-images.githubusercontent.com/105597335/224524580-100a1ab1-284d-4d5d-8458-0d8bb4ed2967.png)
附上自己使用的功能列表
![屏幕截图 2023-03-12 121354](https://user-images.githubusercontent.com/105597335/224524604-afb6b3ad-d0b4-4e7a-88ef-608db8cda151.png)

另外歌词的上浮有点生硬，说不出的感觉，但与am对比就有感知

感谢作者付出！

**Comment by Steve-xmh** [comment]
第一个是已知问题，正在想办法解决
第二个比较细节，做的时候因为成品自我感觉太好了就没磨下去，最后的回弹效果时序和位移量是相等的所以有点不协调，会再优化的

**Comment by 22Frederic** [comment]
谢谢作者！还想问一下，能使用ios端am的英文字体吗，还是我没有设置正确？（苹方和sf pro 均已安装）
![IMG_6273](https://user-images.githubusercontent.com/105597335/224525021-5ee47cf0-2af2-4bd7-9872-e23abc1097f3.PNG)

**Comment by Steve-xmh** [comment]
> 谢谢作者！还想问一下，能使用ios端am的英文字体吗，还是我没有设置正确？（苹方和sf pro 均已安装）
> ![IMG_6273](https://user-images.githubusercontent.com/105597335/224525021-5ee47cf0-2af2-4bd7-9872-e23abc1097f3.PNG)
> 

应该是可以使用 SF Pro 字体的，如果没有成功应用的话检查一下是不是有其他插件的修改字体功能覆盖了 AMLL 插件的字体样式。

**Comment by 22Frederic** [comment]
可以了！是我自己的设置问题
还有一点，字体阴影选项即使关了好像还会有？

**Comment by Steve-xmh** [comment]
> 可以了！是我自己的设置问题
> 还有一点，字体阴影选项即使关了好像还会有？

字体阴影因为之前测试的时候发现如果关掉会导致渲染不正常，所以暂时写死强制启用了，也是之后会想办法让其可以正常工作

**Comment by Steve-xmh** [comment]
已修正歌词间隔错误
