### ISSUE TITLE
【增强】显示歌词贡献者/歌词翻译者等...

### ISSUE THREAD

**Issue by cale044** [Steve-xmh/applemusic-like-lyrics#70]
1. 显示歌词贡献者/歌词翻译者
2. 在歌曲详情页中歌曲名太长不是显示 ... 而是虚化未显示歌曲名
3. 鼠标移动到歌曲名/歌手 太长的歌曲名/歌手滚动显示
4. 音质标签显示在进度条上方 而不是暂停键上方
5. 专辑名在歌曲名下方显示 并且比歌曲名小

**Comment by cale044** [comment]
这里再补充一点 就是列表循环点击两次单曲循环三次心动模式

**Comment by cale044** [comment]
还有就是一起听时在左下角显示一起听时间和头像

**Comment by cale044** [comment]
> 还有就是一起听时在左下角显示一起听时间和头像

配图
![image](https://user-images.githubusercontent.com/123907413/224555642-8d5556de-bbdc-4180-a41e-fd6270d377be.png)

**Comment by Steve-xmh** [comment]
请尽量让多个功能建议分开到单独的 Issue 里，不然根本看不过来也不好完成 Issues

**Comment by cale044** [comment]
> 请尽量让多个功能建议分开到单独的 Issue 里，不然根本看不过来也不好完成 Issues

OK的
