### ISSUE TITLE
网易云音乐使用浅色主题时，标题栏文字可读性较差

### ISSUE THREAD

**Issue by GtxFury** [Steve-xmh/applemusic-like-lyrics#72]
如图，标题栏文字是黑色的，在一些较暗的界面下几乎看不见。
![屏幕截图 2023-03-13 100401](https://user-images.githubusercontent.com/32810165/224591678-fe569f79-7709-4cbf-be5b-5d09507ff252.png)

**Comment by Steve-xmh** [comment]
作者平时常用暗色主题，所以还没有对亮色主题做适配
如果可以的话先暂时使用暗色主题吧，之后这个会做适配的

**Comment by raindropQWQ** [comment]
下方的歌曲评论部分也有相同的问题
![图片](https://user-images.githubusercontent.com/102001942/224702583-dc6ea04e-62bf-4d05-a5d6-3a45b73ade6d.png)
