### ISSUE TITLE
【增强】 专辑名在歌曲名下方显示 并且比歌曲名小

### ISSUE THREAD

**Issue by cale044** [Steve-xmh/applemusic-like-lyrics#78]
如题

**Comment by Steve-xmh** [comment]
专辑名本身并不存在于 Apple Music 中，如果目前影响布局的话可以在设置中隐藏，之后再考虑看要不要做大小调节的功能。

**Comment by Steve-xmh** [comment]
专辑名缩小后不美观，就不考虑了。

**Comment by Steve-xmh** [comment]
> > 专辑名缩小后不美观，就不考虑了。
> 
> 实际上专辑名没必要做的，也许默认隐藏会好一点？

已经是默认隐藏的了
