### ISSUE TITLE
全屏纯享重叠

### ISSUE THREAD

**Issue by maidang2233** [Steve-xmh/applemusic-like-lyrics#8]
![image](https://user-images.githubusercontent.com/50991689/211202243-39f29188-386b-4316-8010-2954179a6b69.png)
全屏纯享重叠

**Comment by Steve-xmh** [comment]
请使用 AMLL 自带的的全屏模式，这个地方的页面适配就不做了。
然后也留意一下 #7 的问题，退出全屏模式也是按这个按钮退出。

![image](https://user-images.githubusercontent.com/39523898/211203006-264db943-e575-4513-9cc7-59fb00f7bad3.png)
