### ISSUE TITLE
在播放页中添加红心（设为喜欢的音乐）按钮

### ISSUE THREAD

**Issue by raindropQWQ** [Steve-xmh/applemusic-like-lyrics#81]
现在想要将歌曲设为红心需要先退出播放界面，然后再在底栏设置
也许可以在现在三点菜单的左边添加这个按钮

**Comment by Steve-xmh** [comment]
菜单按钮左侧不一定好加入这个红心收藏按钮，之后作为菜单的一个项目来提供吧

**Comment by DOGqPolice** [comment]
同需要这个功能。或许可以把播放顺序集中到一个按钮，另一个位置放红心按钮？

**Comment by Steve-xmh** [comment]
> 同需要这个功能。或许可以把播放顺序集中到一个按钮，另一个位置放红心按钮？

主要是希望控制按钮能保持 Apple Music 一致的功能行为，所以不太想动这部分的按钮。

**Comment by cale044** [comment]
> > 同需要这个功能。或许可以把播放顺序集中到一个按钮，另一个位置放红心按钮？
> 
> 主要是希望控制按钮能保持 Apple Music 一致的功能行为，所以不太想动这部分的按钮。

可以加一个可选项就菜单替换成收藏

**Comment by Steve-xmh** [comment]
现在可以通过设置修改左右两侧的控制按钮的功能了：
![image](https://user-images.githubusercontent.com/39523898/229184259-90ddf28c-5507-4f5b-b895-5377c85aed7c.png)
