### ISSUE TITLE
优化一下顶部显示的内容

### ISSUE THREAD

**Issue by 22Frederic** [Steve-xmh/applemusic-like-lyrics#82]
因为主要都是拿来展示的嘛，所以原生网易云上面的很多按钮就显得有点多余，甚至突兀了，希望只保留几个基本的按钮（收起播放页，以及窗口调整的三个按钮）
![5F759363-2347-4574-A1E1-57B713081B9F](https://user-images.githubusercontent.com/105597335/224748281-f065b16c-d6ab-4128-8f22-d30cbe8f59d6.jpeg)

**Comment by Steve-xmh** [comment]
现已隐藏部分组件，只留了返回按钮、全屏纯享和窗口按钮。
