### ISSUE TITLE
2.0 Beta 在关于界面更新后会变成1.87版本

### ISSUE THREAD

**Issue by Pil0tXia** [Steve-xmh/applemusic-like-lyrics#83]
在NCM插件中心中安装的版本号是0.02
启动网易云音乐后提示有可用更新
更新后版本号为1.87
且界面左侧变得只有专辑封面，播放控制组件变成Material You的样式，出现发表评论按钮
希望可以将两个版本分开

**Comment by Steve-xmh** [comment]
请暂时将插件检查更新功能关闭，仅通过插件商店提示进行更新
关于第二个问题，请提供更加详细的信息，例如插件列表，配置文件，截图等。

**Comment by Pil0tXia** [comment]
插件列表：
![image.png](https://s2.loli.net/2023/03/14/S6yWg4dQeYblCwj.png)

从0.02升级到1.87后：
![QQ图片20230314165535.png](https://s2.loli.net/2023/03/14/IOT37kjwHKv49fM.png)

**Comment by Steve-xmh** [comment]
这个只是纯粹被~~更新~~降级到了旧版本了而已，卸载后重新安装 Beta 版本即可
