### ISSUE TITLE
2.0 Beta 不响应蓝牙耳机的播放/暂停命令

### ISSUE THREAD

**Issue by Pil0tXia** [Steve-xmh/applemusic-like-lyrics#84]
耳机为AirpodsPro，按压耳机柄（播放/暂停）时，网易云音乐并没有相应的播放/暂停。卸载插件后恢复正常。

**Comment by Steve-xmh** [comment]
我想可能是网易云的问题，AMLL 没有任何捕获播放快捷键的操作。
我个人的有线耳机的控制按钮也可以正常操作网易云的播放状态。

**Comment by Pil0tXia** [comment]
如果是这样的话，可能是插件运行时软件卡顿导致的。无法进展的话我就关闭issue了。
