### ISSUE TITLE
底部又有一个 “说点什么吧” 非常碍眼 

### ISSUE THREAD

**Issue by Lcode-0403** [Steve-xmh/applemusic-like-lyrics#85]
如题，总体很帅

**Comment by Steve-xmh** [comment]
如果是 AMLL 1.0+ 版本，请安装 TinyNCM 插件后勾选 播放页 - 写评论 即可隐藏。
如果是 AMLL 2.0+ (含 Beta) 版本，则该功能已默认自带，无需安装额外插件。
如果问题是在 AMLL 2.0+ (含 Beta) 中产生的，请再重新开启 Issue，并附上详细信息，例如插件列表，播放页面截图等。
