### ISSUE TITLE
播放界面

### ISSUE THREAD

**Issue by Zhangziqi0** [Steve-xmh/applemusic-like-lyrics#86]
播放界面点击暂停后按钮没有变化，不能再点击进行播放

**Comment by Steve-xmh** [comment]
请提供复现步骤

**Comment by Zhangziqi0** [comment]
播放页面音乐暂停后不能再次播放，按钮一直显示为播放状态
<img width="765" alt="屏幕截图 2023-03-16 114718" src="https://user-images.githubusercontent.com/127876043/225509583-2157d31e-24a8-4780-b0ac-0ea87d7814a7.png">

**Comment by Steve-xmh** [comment]
没有办法复现这个问题出来，能够提供一下你的网易云版本号和 Patch 号（在设置页面底部可以找到）和 BetterNCM 的版本号吗？
如果可能是网易云没有更新的话，可以尝试一下更新网易云版本，看问题有没有解决。

**Comment by Steve-xmh** [comment]
这个版本比我调试的版本还要新……而且我还更新不了……
可能一时半会没有办法修好，等我更新到这个版本吧……
![image](https://user-images.githubusercontent.com/39523898/225944391-65fade8f-a336-4ecd-9acc-058a07f8197f.png)

**Comment by Steve-xmh** [comment]
问题已确认，是 CrossFade LPF 插件未实现一个能表明播放状态事件中的事件参数导致的，请等待作者补充后即可修正问题。

**Comment by fallenleave0620** [comment]
卸载LibFrontendPlay插件可以解决播放页面暂停按钮的问题

**Comment by Zhangziqi0** [comment]
> 卸载LibFrontendPlay插件可以解决播放页面暂停按钮的问题

好的感谢
