### ISSUE TITLE
与CrossFade LPF一起使用会导致随机播放和单曲循环按钮失效

### ISSUE THREAD

**Issue by fallenleave0620** [Steve-xmh/applemusic-like-lyrics#87]
因为不能上传后缀名为json的文件，改为txt上传
[amll-settings.txt](https://github.com/Steve-xmh/applemusic-like-lyrics/files/11008254/amll-settings.txt)
![截图](https://user-images.githubusercontent.com/61518101/226100247-64a32dbe-c407-423b-ba07-fcaa15344ed9.png)

**Comment by Steve-xmh** [comment]
我尝试了你的配置和安装，似乎没有复现出问题。
我个人认为可能和 #86 有关联，能够提供一下你的网易云版本号（包括构建号）和 Patch 号吗？

**Comment by Steve-xmh** [comment]
问题已确认，是 CrossFade LPF 插件未实现一个能表明播放状态事件中的事件参数导致的，请等待作者补充后即可修正问题。
