### ISSUE TITLE
歌词背景

### ISSUE THREAD

**Issue by ROOOOOYczx** [Steve-xmh/applemusic-like-lyrics#9]
歌词背景设置在1.4.4版本更新后设置选项消失

**Comment by Steve-xmh** [comment]
是被我在重构的时候移除了，会准备重写一份新的背景的

**Comment by ROOOOOYczx** [comment]
> 歌词背景设置在1.4.4版本更新后设置选项消失

**Comment by ROOOOOYczx** [comment]
ok谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月9日(星期一) 上午8:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Steve-xmh/applemusic-like-lyrics] 歌词背景 (Issue #9)





 
是被我在重构的时候移除了，会准备重写一份新的背景的
