### ISSUE TITLE
暂停键失效

### ISSUE THREAD

**Issue by raindropQWQ** [Steve-xmh/applemusic-like-lyrics#94]
更新到 0.0.4 后播放界面点击暂停键无反应

网易云版本 2.10.8
![图片](https://user-images.githubusercontent.com/102001942/228779931-66f6d60b-1807-4400-9e23-bfb6fee534fd.png)
但我卸载当前版本安装 2.10.6 后也有同样的问题

**Comment by Steve-xmh** [comment]
已修正
