### ISSUE TITLE
最新的2.0测试版 0.0.4 我更新以后重载网易云就没有其他插件了  关闭以后 网易云就无法打开了

### ISSUE THREAD

**Issue by Nanodayoo** [Steve-xmh/applemusic-like-lyrics#96]

**Comment by Steve-xmh** [comment]
和以下 Issues 相关：
https://github.com/MicroCBer/BetterNCM/issues/352
https://github.com/Steve-xmh/applemusic-like-lyrics/issues/93

**Comment by Nanodayoo** [comment]
已解决 回到1.8.7更新DEV 然后启动再用1.8.7更新beta版本即可解决
