### ISSUE TITLE
2.0 Beta 版本转正式版开发计划

### ISSUE THREAD

**Issue by Steve-xmh** [Steve-xmh/applemusic-like-lyrics#98]
当完成以下功能/修正以下错误并确认没有明显的 Bug 后，将会着手转入正式版本分支：

- [x] #95 
- [x] #94 
- [x] #81 , #80 
- [x] #76 , #75
- [x] #99
- [x] #102 
- [x] #100
- [x] #101 
- [x] #104
- [x] #109

功能项目会根据实际情况继续增加内容。

其他没有列出的功能项目，可能会推到日后完善，敬请期待。

**Comment by cale044** [comment]
终于

**Comment by Yeliaoyuan** [comment]
终于要接入正式版了！

**Comment by Steve-xmh** [comment]
感谢各位的支持，2.0.0 现已正式合并正式版！

原开发分支 `2.0-dev` 和 `2.0-beta` 也将完成使命，分支将会被删除，日后的开发将会由 `dev` 开发分支接替！
