### ISSUE TITLE
音质标签位置有点靠下

### ISSUE THREAD

**Issue by 22Frederic** [Steve-xmh/applemusic-like-lyrics#99]
杜比的还好，无损的那两个就有点明显了，希望能和播放时长在一条中轴线上
![屏幕截图 2023-03-31 230126](https://user-images.githubusercontent.com/105597335/229157937-d776676d-d7e0-4ee7-b1e4-a3a9191c3b0f.png)

**Comment by Steve-xmh** [comment]
已优化
